import type { BriefingConfig } from '@/components/MissionBriefing';

const briefing: BriefingConfig = {
  codigo: 'MEC-105',
  titulo: 'Analiza una Transmisión Hidrostática Bomba-Motor',
  subtitulo: 'Hidráulica y Neumática · T = Δp·D/2π + Wilson: la transmisión sin marchas y el aceite que se elige solo',
  acento: '#EFB13A',
  duracion: 45,
  videoUrl: '',
  bienvenida: `Una transmisión hidrostática no tiene marchas. Tiene un plato inclinado, dos máquinas volumétricas y un lazo cerrado de aceite entre ellas. Y la primera cosa que hay que desaprender es que el par lo pone el plato.

El par lo pone la PRESIÓN, y la ley cabe en cinco caracteres: T = Δp·D/2π. El motor de 45 cm³/rev que mueve la cargadora tiene que dar 280 N·m, así que el aceite tiene que llegarle a 391,0 bar ideales —417,4 reales cuando le sumas el arrastre y la fricción—. Pon 28 cm³/rev y esos mismos 280 N·m piden 655,1 bar: el grupo aguanta 420. Pon 107 y bastan 178,5, pero entonces el mando α tiene que valer 1,248, o sea más plato del que existe. Entre esos dos muros —la presión por un lado, el tope del plato por el otro— hay una franja estrecha donde la máquina existe. El resto del catálogo es hierro que no rueda.

Lo segundo es que la relación de transmisión que mides en los ejes NUNCA es la que dice la geometría. La geométrica vale D_b·α/D_m; la cinemática es n_m/n_b; y entre ellas está exactamente el producto de los rendimientos volumétricos: relCin = relGeom·η_vb·η_vm. Despéjalo y el deslizamiento es literalmente 1 − η_vb·η_vm. Lo incómodo es que no se ve: en la cargadora, con las cinco bombas del catálogo, la relación cinemática se queda clavada en 0,500 mientras el deslizamiento sube del 9,60 al 11,26 %. El regulador tapa la fuga subiendo α, y el tacómetro no te va a avisar.

Lo tercero es el modelo de Wilson, de 1946, que sigue siendo la forma honesta de contar estas pérdidas: σ = K_S·Δp/(μ·ω) para la fuga, τ = K_V·μ·ω/Δp para el arrastre viscoso, más un coeficiente de Coulomb. Multiplica los dos y la viscosidad se va, y el régimen se va, y la presión se va: σ·τ = K_S·K_V = 0,0016, una constante del par de máquinas. Está verificado en 80 puntos de trabajo distintos con desviación menor que 1e-18. Significa que no puedes bajar las dos pérdidas a la vez: lo que le quitas a la fuga se lo regalas al arrastre.

Lo cuarto te va a cambiar la forma de leer una ficha técnica: la temperatura del aceite NO es un dato de entrada, es una SALIDA. Aquí se resuelve como punto fijo de calor(T) = UA·(T − T_amb). El mismo hierro se estabiliza a 49,9 °C en la cargadora, a 28,6 en el cabrestante forestal que trabaja a 12 °C de ambiente, y a 77,1 en el ventilador de radiador, que está a 50 °C ambiente y sólo puede evacuar 0,14 kW/K.

Y de ahí sale lo que menos gente espera. Los cuatro grados ISO VG del catálogo se diferencian en 3,13 veces a 40 °C. En equilibrio, esa horquilla se estrecha a 2,99 · 2,33 · 3,06 · 1,76 y 2,19 según la estación, porque el aceite espeso arrastra más, calienta más y se adelgaza SOLO. En el ventilador, elegir entre VG 32 y VG 100 mueve la viscosidad de servicio de 9,9 a 17,4 mm²/s: la mitad de lo que prometía la etiqueta del bidón.

Lo quinto es la ley del aceite: cada máquina pide el suyo. La viscosidad óptima es proporcional a Δp/ω, así que la máquina que gira más deprisa pide el aceite más fino, y el conjunto se queda siempre en un compromiso ENTRE los dos. En la cargadora son 27,2 para la bomba, 48,7 para el motor y 36,5 para el conjunto. En el cabrestante, que gira a 200 rpm, el motor pediría 206,8 mm²/s. En el ventilador, que gira a 2 600, pide 3,3.

El banco tiene cinco estaciones industriales y 1 500 configuraciones (5 bombas × 5 motores × 4 aceites × 3 regímenes × 5 estaciones). Siete criterios que hay que cumplir a la vez, y sólo 123 lo consiguen; en el ventilador de radiador sobreviven TRES de 300. Motor verificado con 284 183 comprobaciones numéricas, 0 fallos, y la simulación con 386 aserciones en navegador real.`,
  conceptos: [
    { icono: '⚙️', nombre: 'El par no lo pone el plato: lo pone la presión', descripcion: 'T = Δp·D/2π es la ley entera de una máquina volumétrica, y el laboratorio la verifica a 1e-12 junto con su proporcionalidad estricta. Los 280 N·m de la cargadora piden 391,0 bar ideales con un motor de 45 cm³/rev y 417,4 reales; con 28 cm³/rev piden 655,1 y el grupo aguanta 420; con 107 bastan 178,5 pero el mando α tendría que valer 1,248. La cilindrada del motor no elige cuánto par hay, elige contra qué muro chocas: el límite de presión por abajo o el tope del plato por arriba. Y la presión no se ajusta: se DESPEJA del punto de servicio, porque el término viscoso del motor no depende de Δp.' },
    { icono: '🔁', nombre: 'La relación que mides no es la que dice la geometría', descripcion: 'relGeom = D_b·α/D_m es lo que dice el hierro; relCin = n_m/n_b es lo que dice el tacómetro; y entre ellas está exactamente relCin = relGeom·η_vb·η_vm, de donde desliz = 1 − η_vb·η_vm. Es una identidad, no una aproximación, y el laboratorio la comprueba en todo el barrido. Lo peligroso es que el regulador de la bomba la ESCONDE: en la cargadora, con las cinco bombas del catálogo, la relación cinemática vale 0,500 en las cinco mientras el deslizamiento sube del 9,60 al 11,26 %. El aceite que se pierde se paga en α, en presión de carga y en calor, nunca en revoluciones.' },
    { icono: '♾️', nombre: 'σ·τ es una constante: no puedes ganar las dos', descripcion: 'El modelo de Wilson (1946) separa la fuga (σ = K_S·Δp/(μ·ω)) del arrastre viscoso (τ = K_V·μ·ω/Δp). Multiplícalos y desaparecen la viscosidad, el régimen y la presión: σ·τ = K_S·K_V = 0,0016 en cualquier punto de trabajo —verificado en 80 puntos con desviación menor que 1e-18—. Aceite fino: menos arrastre, más fuga. Aceite espeso: al revés. El rendimiento total es el producto de cuatro términos en cascada, η_vb·η_tb·η_vm·η_tm, y en los cinco óptimos del banco vale 79,54 · 79,98 · 73,24 · 72,02 y 79,85 %; el de sistema, que además paga la bomba de carga, baja a 78,62 · 78,78 · 71,56 · 68,28 y 78,60 %.' },
    { icono: '🌡️', nombre: 'La temperatura es una salida, y el aceite se elige solo a medias', descripcion: 'calor(T) = UA·(T − T_amb) es un punto fijo, no un dato: el mismo hierro se estabiliza a 49,9 °C en la cargadora, 28,6 en el cabrestante (12 °C de ambiente) y 77,1 en el ventilador (50 °C ambiente, 0,14 kW/K de disipación). Y como el aceite espeso arrastra más, calienta más y se adelgaza solo, la horquilla de 3,13 veces que separa el VG 32 del VG 100 a 40 °C se estrecha a 1,76…3,06 en equilibrio. Encima cada máquina pide su viscosidad —μ* ∝ Δp/ω, así que el que gira deprisa pide fino— y la del conjunto cae SIEMPRE entre las dos: 27,2 / 36,5 / 48,7 mm²/s en la cargadora, 30,8 / 80,7 / 206,8 en el cabrestante, 5,4 / 4,2 / 3,3 en el ventilador.' },
  ],
  mision: [
    'EL PAR NO SALE DEL PLATO · Modo Par y caudal, estación Cargadora compacta. El motor tiene que dar 280 N·m a 900 rpm. Lee en la telemetría la Δp ideal (T·2π/D = 391,0 bar con 45 cm³/rev) y la Δp real que hace falta, 417,4, con la diferencia repartida entre el arrastre viscoso y la fricción de Coulomb. Ahora baja la cilindrada del motor a 28 cm³: la presión se dispara a 655,1 bar contra los 420 que aguanta el grupo. Súbela a 107: bajas a 178,5 pero el mando α pide 1,248 y no existe tanto plato. El par es el mismo en los cinco casos; lo que cambia es contra qué muro chocas.',
    'EL DESLIZAMIENTO QUE EL TACÓMETRO NO ENSEÑA · Modo Relación de transmisión, cargadora con motor de 45 cm³ y VG 46 a 1 800 rpm. Recorre las cinco bombas del catálogo y anota la relación cinemática: 0,500 en las cinco. Ahora mira el deslizamiento: 9,60 · 9,87 · 10,29 · 10,62 · 11,26 %. El regulador ha subido α para tapar la fuga y el tacómetro no se ha enterado. Comprueba en la telemetría la identidad relCin = relGeom·η_vb·η_vm y saca la consecuencia: en una transmisión hidrostática el aceite perdido no se ve en revoluciones, se ve en mando, en presión de carga y en temperatura.',
    'LA CONSTANTE QUE PROHÍBE GANAR DOS VECES · Modo Rendimiento del conjunto. Cambia el aceite, cambia el régimen del diésel, cambia la estación, y vigila el producto σ·τ: vale 0,0016 siempre, en la bomba y en el motor, porque es K_S·K_V y ahí no quedan ni viscosidad ni régimen ni presión. Es la razón física de que no exista el aceite perfecto: lo que le quitas a la fuga se lo regalas al arrastre. Comprueba después la cascada η_vb·η_tb·η_vm·η_tm y fíjate en que el motor de una hidrostática pierde DOS veces lo mismo que la bomba, en el mismo orden y por los mismos dos mecanismos.',
    'LA TEMPERATURA ES UNA SALIDA · Modo El aceite decide, con el hierro del óptimo montado. Busca en la gráfica el cruce entre el calor generado y el que la máquina puede evacuar: ahí está la temperatura de servicio, y no la has elegido tú. Recorre las cinco estaciones: 49,9 · 64,3 · 28,6 · 77,1 · 51,2 °C. El cabrestante forestal trabaja a 12 °C de ambiente y se queda en 28,6; el ventilador de radiador está a 50 °C con sólo 0,14 kW/K de disipación y se va a 77,1, a tres grados del límite de servicio continuo del fluido.',
    'EL ACEITE ESPESO SE ADELGAZA SOLO · Sigue en El aceite decide y cambia únicamente el bidón entre los cuatro grados ISO. A 40 °C el VG 100 es 3,13 veces más viscoso que el VG 32; en equilibrio esa horquilla se derrumba a 2,99 en la cargadora y a 1,76 en el ventilador, donde elegir entre uno y otro sólo mueve la viscosidad de servicio de 9,9 a 17,4 mm²/s. En la cargadora los cuatro aceites dan 19,4 / 30,0 / 43,0 / 58,0 mm²/s con temperaturas de 52,8 / 50,0 / 49,9 / 51,3 °C: el aceite espeso arrastra más, calienta más y se destempla él solo. La etiqueta del bidón promete a 40 °C; la máquina no trabaja a 40 °C.',
    'CADA MÁQUINA PIDE SU ACEITE · Sigue en El aceite decide y compara las tres viscosidades óptimas que da la telemetría: la de la bomba, la del motor y la del conjunto. En la cargadora son 27,2 / 36,5 / 48,7 mm²/s; en el cabrestante, cuyo motor gira a 200 rpm, el motor pediría 206,8 mientras la bomba pide 30,8; en el ventilador, que gira a 2 600, el motor pide 3,3. La regla es μ* ∝ Δp/ω: la máquina que gira más deprisa pide el aceite más fino, y la del conjunto cae SIEMPRE entre las dos. Comprueba también que ese óptimo del sistema es un máximo de verdad perturbándolo un ±20 %.',
    'SIETE CRITERIOS QUE DECIDEN DE VERDAD · Abre el censo del barrido: 1 500 configuraciones, 123 válidas, 15 que ni siquiera son físicas. Mira los fallos en solitario —13 el cierre térmico, 40 la reserva de mando, 58 la presión del grupo, 164 la potencia del diésel, 53 la ventana de viscosidad, 165 el régimen del bloque de pistones y 1 el caudal de la bomba de carga— y comprueba que los siete criterios pueden tumbar una máquina ellos solos. Ese único caso del caudal de carga es el más instructivo del banco: todo lo demás sobraba y la máquina no arranca porque no hay con qué reponer la fuga.',
    'RETO · Se sortea una estación y arrancas con los cuatro ejes mal a propósito: cilindrada de la bomba, cilindrada del motor, grado del aceite y régimen del diésel. Cada eje se califica POR SEPARADO con los otros tres ya en su óptimo, así que sabrás cuál fallaste sin que te den la respuesta. Cumplir los siete criterios no basta: hay que montar el conjunto válido más barato y, a igualdad de coste, el que menos kWh consuma al año. Ojo con la pista: es honesta, y por eso a veces sale vacía —desde el arranque equivocado, en 19 de 20 casos no existe ningún valor de ese eje que salve la configuración—. Y si te toca el ventilador de radiador, ten paciencia: de sus 300 configuraciones sobreviven TRES.',
  ],
  aplicaciones: [
    { area: 'Dimensionado de la transmisión de una máquina móvil', ejemplo: 'Cargadoras, cosechadoras, tambores de hormigonera, cabrestantes y ventiladores reversibles: todo accionamiento donde el par y el régimen los fija la máquina y lo que se elige es el hierro que los da. Este laboratorio pone sobre la mesa los siete criterios que hay que cumplir a la vez —cierre térmico, reserva de mando, presión del grupo, potencia del diésel, ventana de viscosidad del fabricante, régimen máximo del bloque de pistones y caudal de la bomba de carga— y demuestra que se pelean entre ellos: el motor grande baja la presión y se come el plato, el motor pequeño ahorra plato y revienta el límite del grupo, y el diésel rápido da potencia y tumba el régimen admisible del bloque. De 1 500 configuraciones sólo 123 sobreviven, y en el ventilador de radiador únicamente 3 de 300.' },
    { area: 'Diagnóstico de una hidrostática que ha perdido prestaciones', ejemplo: 'Es la avería típica de la máquina con horas: «va más lenta» o «se calienta». Aquí se mide su mecánica real. El deslizamiento 1 − η_vb·η_vm no se ve en el tacómetro porque el regulador lo compensa subiendo α, así que el síntoma útil no es la velocidad sino el mando, el caudal de carga y la temperatura de equilibrio. El laboratorio muestra el reparto exacto entre fuga y arrastre en las dos máquinas, la constante σ·τ que impide bajarlos a la vez, y por qué subir de grado de aceite para «tapar la fuga» sube el calor y devuelve la viscosidad casi al mismo sitio: en el ventilador, cambiar de VG 32 a VG 100 sólo mueve el servicio de 9,9 a 17,4 mm²/s.' },
    { area: 'Selección del aceite y proyecto de la refrigeración', ejemplo: 'Dos decisiones que en la práctica se toman por separado y aquí se demuestran acopladas. El aceite se elige por su viscosidad a la TEMPERATURA DE SERVICIO, no a 40 °C, y esa temperatura es una salida del balance calor(T) = UA·(T − T_amb): la misma máquina se queda en 28,6 °C en monte a 12 °C de ambiente y en 77,1 en el hueco del radiador a 50 °C. Con la ley μ* ∝ Δp/ω se justifica por qué un motor lento pide aceite espeso y una bomba rápida lo pide fino, y por qué el óptimo del conjunto es siempre un compromiso entre los dos. Y el consumo anual —46 991 · 24 883 · 12 643 · 31 102 y 66 825 kWh en las cinco estaciones del banco— convierte un punto de rendimiento en una cifra de factura, que es el argumento que se defiende delante de quien paga.' },
  ],
};

export default briefing;
