import type { BriefingConfig } from '@/components/MissionBriefing';

const briefing: BriefingConfig = {
  codigo: 'MEC-84',
  titulo: 'Temporizadores y Contadores en Secuencias',
  subtitulo: 'Sistemas Digitales · Bloques funcionales de PLC · IEC 61131-3: TON, TOF, TP, CTU y CTD, y la secuencia por etapas',
  acento: '#8AB4F8',
  duracion: 30,
  videoUrl: '',
  bienvenida: `Un extractor que sigue aspirando medio minuto después de que apagas la máquina. Un horno que no enciende las resistencias hasta que el ventilador lleva tres segundos girando. Una envasadora que cuenta diez botellas y cierra la caja. Ninguna de esas tres cosas se puede programar con contactos y bobinas: la lógica de contactos sabe decir "si esto y aquello, entonces", pero no sabe decir "espera", "sigue un rato más" ni "cuenta hasta diez".

Para eso la IEC 61131-3 define BLOQUES FUNCIONALES con MEMORIA PROPIA. Cada instancia de un temporizador guarda su tiempo transcurrido (ET) de un ciclo de scan al siguiente; cada instancia de un contador guarda su cuenta (CV). Los tres temporizadores comparten exactamente las mismas entradas —IN (la orden) y PT (la preselección de tiempo)— y las mismas salidas —Q y ET—, y aun así NO son intercambiables. El TON retrasa el ENCENDIDO: empieza a contar cuando IN se pone a 1 y activa Q al alcanzar PT, pero su Q cae en el mismo instante que IN. El TOF retrasa el APAGADO: Q sube con IN y sigue activa PT DESPUÉS de que IN caiga; además es REDISPARABLE, así que si la orden vuelve dentro del retardo la cuenta empieza de nuevo. Y el TP entrega un PULSO de anchura fija PT que NO es redisparable: los flancos que lleguen durante el pulso se ignoran, de modo que aporrear un botón no alarga ni multiplica la acción. Elegir mal entre los tres no da "casi lo mismo": da un comportamiento distinto.

Los contadores resuelven otro problema. CTU y CTD cuentan FLANCOS de subida, no niveles: mantener la entrada alta durante veinte ciclos cuenta una sola vez. El CTU activa Q cuando CV ≥ PV y su entrada R es dominante; el CTD, cargado antes con LD, activa Q cuando CV ≤ 0 —y si no lo cargas, arranca en cero con Q ya activa, que es la falsa alarma más clásica del principiante. Contar sucesos y medir tiempo son magnitudes distintas: si las piezas llegan con cadencia irregular, no existe ningún PT que equivalga a "diez piezas".

Cuando estos bloques se encadenan aparece la estructura básica de cualquier proceso por lotes: un TON por ETAPA que, al cumplir su PT, salta a la siguiente y re-arma el temporizador —así cada etapa dura exactamente su PT y el ciclo es la suma de los PT— mientras un CTU cuenta los ciclos y cierra el lote al llegar a PV. En este laboratorio conducirás los cinco bloques ciclo a ciclo sobre una base de scan idealizada de 100 ms, los compararás ante el mismo estímulo y programarás las tres funciones típicas de una máquina real. La lógica se verificó numéricamente 33/33, incluida la unicidad de la solución del reto en sus cuatro escenarios.`,
  conceptos: [
    { icono: '⏱️', nombre: 'TON — retrasa el encendido', descripcion: 'Empieza a contar en el flanco de subida de IN y activa Q cuando ET alcanza PT; Q cae en el mismo scan que IN. Si IN cae antes de PT, ET se borra y hay que empezar de cero: por eso el TON también es un excelente filtro antirruido, porque una señal que no se mantiene no dispara nada.' },
    { icono: '🌬️', nombre: 'TOF — retrasa el apagado', descripcion: 'Q sube con IN y sigue activa PT después de que IN caiga, y luego se apaga sola. Es REDISPARABLE: si la orden vuelve dentro del retardo, la cuenta se reinicia. Arranca con ET precargado en PT, de modo que Q vale 0 al energizar el PLC y no hay pulso espurio. Es el bloque de la purga y la sobre-marcha.' },
    { icono: '📏', nombre: 'TP — pulso de anchura fija', descripcion: 'Un flanco de subida lanza un pulso que dura exactamente PT, pase lo que pase con IN después. NO es redisparable: los flancos durante el pulso se ignoran. Es el bloque de las dosificaciones por tiempo, los avisos y los impulsos de reset, donde la duración de la acción debe estar garantizada.' },
    { icono: '🔢', nombre: 'CTU / CTD — cuentan flancos, no niveles', descripcion: 'El CTU suma uno por cada flanco de subida de CU y activa Q cuando CV ≥ PV, con R dominante; el CTD carga PV con LD y resta hasta que CV ≤ 0. Mantener la entrada alta no sigue contando. Contar sucesos no es medir tiempo: con cadencia irregular, ningún temporizador puede sustituir a un contador.' },
  ],
  mision: [
    'EXPLORA · Conduce cada bloque ciclo a ciclo, donde cada pulsación de la botonera es un scan de 100 ms. Con el TON mantén IN = 1 y ve crecer ET hasta que Q dispara; luego suelta IN antes de llegar a PT y comprueba que ET se borra. Cambia al TOF, sube IN un par de scans y suéltalo: Q seguirá activa PT más y caerá sola. Prueba el TP y verás que el pulso dura siempre lo mismo. Con el CTU pulsa "▲" dos veces seguidas: la cuenta sólo avanza una vez, porque cuenta flancos.',
    'APLICA · Compara y encadena. En "TON vs TOF vs TP" el mismo estímulo alimenta los tres temporizadores con el mismo PT y se dibujan los tres cronogramas apilados: busca el pulso corto de un solo scan, que el TON no llega a disparar pero el TP sí. En "Secuencia + lote" estudia la cascada de TON de una receta de tres etapas: las transiciones que se muestran están MEDIDAS ejecutando el programa, cada etapa dura exactamente su PT y el CTU cierra el lote al llegar a PV.',
    'RETO · Programa las tres funciones de una máquina real —retardo de arranque, sobre-marcha tras el paro y conteo del lote— eligiendo el BLOQUE y su PRESELECCIÓN. Cada elección se simula sobre el mismo motor verificado y se califica por separado: acertar el tipo con el tiempo equivocado sigue estando mal. Las unidades llegan con cadencia irregular, así que ningún temporizador puede contarlas. Errores clásicos: TP para un retardo, TON para la purga y CTD sin cargar con LD.',
  ],
  aplicaciones: [
    { area: 'Arranques secuenciados y purgas en máquinas', ejemplo: 'Un TON impide energizar el equipo principal antes de que el auxiliar esté listo: las resistencias de un horno no encienden hasta que el ventilador de circulación lleva unos segundos girando, y una prensa no habilita hasta que el lubricador de línea está activo. En el paro pasa lo contrario: un TOF mantiene el extractor aspirando o el ventilador purgando calor después de la orden de paro, para que la máquina no quede con virutas dentro ni el horno se cocine a sí mismo.' },
    { area: 'Dosificación, conteo y control de lotes', ejemplo: 'Un TP abre una electroválvula exactamente el tiempo de una dosis, sin que dependa de cuánto sostenga el operario el botón. Un CTU cuenta piezas, botellas o vueltas de un eje con un encoder de un pulso y avisa "lote completo" para que el sistema cierre la caja, cambie de tarima o pare la línea; su entrada R deja el contador listo para el siguiente lote. Un CTD hace lo mismo en regresivo: cargar con LD las N unidades pendientes y descontar hasta cero.' },
    { area: 'Procesos por lotes y evolución hacia GRAFCET', ejemplo: 'Reactores de mezclado, túneles de lavado, cabinas de pintura y ciclos de tratamiento térmico se programan como una cadena de etapas temporizadas: un TON por etapa, re-armado en cada transición, y un contador de ciclos. Esa estructura es la que la IEC 60848 formaliza en GRAFCET/SFC cuando el proceso crece y aparecen ramas, saltos y etapas simultáneas; entender la cascada de temporizadores es el paso previo obligado para leer un GRAFCET real.' },
  ],
};

export default briefing;
