import type { CatalogoEntry } from '../_types';

const catalogo: CatalogoEntry = {
  modulo: "Sistemas Digitales",
  titulo: "Temporizadores y Contadores en Secuencias",
  duracion: "30 min",
  teoria: "La lógica de contactos sabe decir \"si esto y aquello, entonces\", pero no sabe decir \"espera\", \"sigue un rato más\" ni \"cuenta hasta diez\". Para eso la IEC 61131-3 define bloques funcionales con memoria propia: cada instancia guarda su tiempo transcurrido ET o su cuenta CV de un ciclo de scan al siguiente. Los tres temporizadores comparten las mismas entradas (IN, PT) y salidas (Q, ET) y aun así no son intercambiables: el TON retrasa el ENCENDIDO —Q sube cuando ET alcanza PT y cae en el mismo scan que IN, y si IN cae antes ET se borra, lo que lo convierte además en un filtro antirruido—; el TOF retrasa el APAGADO —Q sube con IN y sigue activa PT después de que IN caiga, es redisparable y arranca con Q = 0 al energizar el PLC—; y el TP entrega un pulso de anchura fija PT que no es redisparable, de modo que aporrear el botón no alarga ni multiplica la acción. Los contadores resuelven otra magnitud: CTU y CTD cuentan FLANCOS de subida, no niveles, así que mantener la entrada alta cuenta una sola vez; el CTU activa Q cuando CV ≥ PV con R dominante y el CTD, cargado antes con LD, cuando CV ≤ 0 —sin cargarlo arranca en cero con Q ya activa, la falsa alarma clásica—. Contar sucesos y medir tiempo son cosas distintas: si las unidades llegan con cadencia irregular, no existe ningún PT equivalente a \"diez piezas\". Encadenando un TON por etapa, re-armado en cada transición, cada etapa dura exactamente su PT y el ciclo es la suma de los PT, mientras un CTU cuenta los ciclos y cierra el lote al llegar a PV: ésa es la estructura básica de un reactor de mezclado, un túnel de lavado o una cabina de pintura, y el paso previo obligado para leer un GRAFCET. El laboratorio conduce los cinco bloques ciclo a ciclo sobre una base de scan idealizada de 100 ms, los compara ante el mismo estímulo y pide programar el retardo de arranque, la sobre-marcha tras el paro y el conteo del lote de una máquina real, calificando cada elección por comportamiento sobre el mismo motor verificado (33/33). Sí modela la semántica exacta de TON, TOF, TP, CTU y CTD y la secuencia por etapas con contador de lote; NO modela el tiempo real de scan ni su jitter, la cuantización cuando PT no es múltiplo del scan, los temporizadores retentivos TONR/RTO, los contadores CTUD, las instrucciones de flanco R_TRIG/F_TRIG, el rebote de los sensores, la retención de CV ante corte de alimentación ni el juego de instrucciones de ningún PLC comercial. Referencias: IEC 61131-3; Petruzella, Programmable Logic Controllers; Bolton, Programmable Logic Controllers; Hackworth, Programmable Logic Controllers; IEC 60848 (GRAFCET).",
  estado: "activo",
  simuladorHtml: "/labs/temporizadores-contadores-plc.html",
};

export default catalogo;
