import type { BriefingConfig } from '@/components/MissionBriefing';

const briefing: BriefingConfig = {
  codigo: 'MEC-85',
  titulo: 'Arranque Estrella-Delta Temporizado',
  subtitulo: 'Sistemas Digitales · Maniobra de contactores · IEC 61131-3 + IEC 60947-4-1: tiempo muerto, enclavamiento y contactos espejo',
  acento: '#8AB4F8',
  duracion: 30,
  videoUrl: '',
  bienvenida: `Un motor de jaula con los seis terminales del bobinado accesibles puede arrancarse primero en ESTRELLA —cada devanado recibe la tensión de línea dividida entre √3, de modo que la corriente y el par caen a la tercera parte— y pasarse a DELTA cuando ya aceleró. Esa parte, la eléctrica, ya la trabajaste en MEC-50. Aquí miramos el otro lado del arrancador: el PROGRAMA DE MANIOBRA.

Son tres contactores —KM1 de línea, KMY de estrella y KMΔ de delta— gobernados por dos temporizadores TON: el primero fija cuánto dura la estrella y el segundo abre el TIEMPO MUERTO de la transición. Lo que convierte esto en un problema de ingeniería y no en una receta es que la ORDEN que escribe el PLC y el ESTADO REAL DEL CONTACTO no son la misma cosa. La bobina obedece dentro del ciclo de scan, pero la armadura tiene masa: los contactos tardan un tiempo de cierre en cerrar y un tiempo de apertura en abrir, y este último incluye la extinción del arco. Si KMΔ cierra antes de que KMY termine de abrir, los dos quedan cerrados a la vez y el bobinado cortocircuita dos fases. Eso no es un fallo de programación cualquiera: funde fusibles, suelda contactos y puede destruir el motor.

De ahí salen las tres lecciones. Primera: el enclavamiento por SOFTWARE —condicionar cada bobina a la variable interna de la otra— impide el error de programación, pero no el solape físico, porque sólo lee variables del PLC: cuando el programa quita la orden a KMY, la variable cae en ese mismo scan y el software da permiso a KMΔ mientras el metal sigue cerrado. Segunda: el TIEMPO MUERTO sí impide el solape, pero debe ser el MÁS CORTO que lo consiga, porque la transición es ABIERTA —durante el tiempo muerto el motor queda desenergizado, su fem residual decae y se desfasa de la red al ritmo del deslizamiento— y el pico de corriente al reconectar crece con él en todo el rango que un arrancador puede ajustar, hasta su máximo en la oposición de fase. Tercera: contra un contactor SOLDADO ningún tiempo muerto sirve, por largo que sea; sólo los CONTACTOS ESPEJO del Anexo F de la IEC 60947-4-1, que leen el contacto de verdad y garantizan constructivamente que su auxiliar NC no esté cerrado a la vez que ningún principal NA, dan una falla segura: KMΔ no llega ni a energizarse y el motor se queda en estrella sin daño.

Conducirás el contactor scan a scan, medirás el cronograma de la conmutación con la banda de solape, verás las dos curvas del compromiso y ajustarás el arrancador de una máquina real. La lógica de maniobra se verificó numéricamente 38/38, incluida la unicidad y la ortogonalidad de la solución del reto en sus cuatro escenarios.`,
  conceptos: [
    { icono: '⚡', nombre: 'La orden no es el contacto', descripcion: 'La bobina cambia de estado dentro de un ciclo de scan, pero la armadura tiene masa: el contacto cierra en t_cierre y abre en t_apertura, y este último incluye la extinción del arco. Todo el problema del arranque estrella-delta cabe en esa distinción, y los dos tiempos son dato de catálogo del fabricante, no una suposición.' },
    { icono: '⏱️', nombre: 'Tiempo muerto = ventana de peligro', descripcion: 'La ventana en que KMY sigue cerrado después de que KMΔ ya cerró dura exactamente t_apertura − t_cierre. El solape medido resulta ser máx(0, t_apertura − t_cierre − tiempo muerto): el tiempo muerto correcto es el más corto que lo anula, porque alargarlo hace crecer el pico de reconexión.' },
    { icono: '🔒', nombre: 'Enclavamiento por software ≠ protección', descripcion: 'Condicionar cada bobina a la variable interna de la otra evita el error de programación —que el programa mande las dos a la vez—, pero no el solape físico: la variable cae en el mismo scan en que se quita la orden, mientras el metal sigue cerrado. Es una protección contra el programador, no contra la física.' },
    { icono: '🪞', nombre: 'Contactos espejo (IEC 60947-4-1, Anexo F)', descripcion: 'Contacto auxiliar NC con garantía constructiva de no estar cerrado a la vez que ningún principal NA. Es la única protección que sobrevive a un contactor soldado: si KMY se pega, KMΔ ni siquiera se energiza y el motor se queda en estrella. Falla segura, visible y sin daño; en obra se cablea además en serie con las bobinas, fuera del PLC.' },
  ],
  mision: [
    'EXPLORA · Conduce el contactor de un equipo scan a scan, donde cada pulsación de la botonera es un ciclo de 5 ms. Mantén la orden en 1 y cuenta cuántos scans tardan los contactos en cerrar; luego quítala y cuenta los que tardan en abrir. Los dos números no son iguales, y su diferencia —que el panel muestra— es la ventana de cortocircuito de la que trata toda la práctica.',
    'APLICA · Tres estudios. En "Conmutación Y→Δ" ves una ventana de 400 ms alrededor del cumplimiento del temporizador de estrella, con la orden de bobina punteada y el contacto real continuo: empieza con tiempo muerto cero y aparece la banda roja del solape; cambia a enclavamiento por software y comprueba que apenas se mueve. En "Solape vs pico" las dos curvas del compromiso se oponen: el solape cae a cero en el umbral y el pico de reconexión no deja de crecer en todo el rango ajustable. En "Falla: KMY soldado" comparas los tres enclavamientos en paralelo: contra una soldadura, el tiempo no protege.',
    'RETO · Ajusta el arrancador de una máquina asignada en tres decisiones independientes: el tiempo en estrella (la opción más corta cuyo deslizamiento ya esté por debajo del máximo admisible), el tiempo muerto (que se deduce de los tiempos de catálogo del contactor y se evalúa SIN ayuda del enclavamiento) y el enclavamiento (que se decide pensando en el ensayo del contactor soldado). Cada criterio se simula por separado sobre el motor verificado, así que acertar dos de tres sigue siendo un arrancador mal ajustado. El programa de partida está deliberadamente mal en las tres.',
  ],
  aplicaciones: [
    { area: 'Arrancadores de motores en la industria', ejemplo: 'Bombas centrífugas, ventiladores, compresores de tornillo y bandas transportadoras arrancan en estrella-delta cuando la red no admite la corriente de arranque directo y la carga puede acelerar con un tercio del par. El tablero de maniobra es exactamente el de esta práctica: tres contactores, dos temporizadores y un enclavamiento; y el ajuste del tiempo de estrella y del tiempo muerto es el trabajo que hace el técnico en la puesta en marcha, con los tiempos de operación del catálogo del contactor en la mano.' },
    { area: 'Seguridad funcional y ensayos de aceptación', ejemplo: 'Las maniobras donde dos contactores nunca deben cerrar a la vez —inversión de giro, conmutación red/grupo electrógeno, transferencia de alimentación— se validan con el mismo ensayo: soldar (o simular) un contacto principal y comprobar que el sistema falla de forma segura. Ahí es donde se separa el enclavamiento por software del cableado con contactos espejo o mecánicamente ligados de la IEC 60947, que son los que la norma admite como medida de protección.' },
    { area: 'Migración a arrancadores suaves y variadores', ejemplo: 'El pico de reconexión de la transición abierta y la limitación de "sólo un tercio del par en el arranque" son precisamente los argumentos que empujan a sustituir el estrella-delta por un arrancador suave o un variador de frecuencia. Entender qué compromiso se está resolviendo con el tiempo muerto permite justificar técnicamente esa sustitución —o defender que el estrella-delta sigue siendo suficiente y mucho más barato— en lugar de decidirlo por costumbre.' },
  ],
};

export default briefing;
