import type { BriefingConfig } from '@/components/MissionBriefing';

const briefing: BriefingConfig = {
  codigo: 'MEC-97',
  titulo: 'Lógica Neumática Y/O y Temporización',
  subtitulo: 'Hidráulica y Neumática · ISO 1219-1 + ISO 6358 + ISO 8778 + ISO 15552 + ISO 4414: en neumática el 1 lógico tiene un valor en bar, y el retardo no se elige, se calcula',
  acento: '#4FC3B0',
  duracion: 40,
  videoUrl: '',
  bienvenida: `En lógica digital un 1 es un 1. En neumática no: el 1 lógico es una presión, y esa presión se puede degradar hasta dejar de ser un 1 sin que se rompa nada. Ahí está toda la práctica. La válvula de simultaneidad (función Y) entrega el MÍNIMO de sus dos entradas y la selectora (función O) entrega el MÁXIMO. Por eso la estación de encolado, cuya segunda entrada es una rama regulada a 2 bar, se queda bloqueada con una simultaneidad perfectamente sana: min(6; 2) = 2,00 bar y el pilotaje pide 2,5. No hay avería que buscar — hay que comprar un relevador de baja presión que dispare a 1,2 bar y reponga la línea a 6.

También hay que aprender a NO comprar. Dos válvulas 3/2 en serie hacen la función Y con cero componentes añadidos, y en la prensa de embutido ésa es la solución mínima: la simultaneidad ahí es dinero tirado. Pero el truco tiene un límite topológico que no es de presión sino de arquitectura: en serie sólo se pueden encadenar dos ÓRGANOS alimentados por la misma línea; si una de las entradas es una señal ya generada aguas arriba, la serie no existe. Y del otro lado está el empalme en T, el atajo que todo el mundo monta para hacer una O: nunca es válido, pero casi siempre «funciona». En la puerta de horno funciona tan mal que enseña el síntoma clásico de taller — desde el pedal llegan 5,85 bar y arranca, desde el pulsador del panel llegan 1,00 bar y no arranca, y por el nodo se escapan 149 l/min a la atmósfera: 71,5 m³ por turno, 7,9 kWh tirados por un empalme de dos pesos.

La segunda mitad es el tiempo. El retardo neumático no se elige en un menú: se integra. El depósito se llena a través del estrangulador siguiendo la ISO 6358 —tramo sónico Q = C·p1 mientras la relación de presiones está por debajo de b = 0,45, y tramo subsónico con la elipse por encima— hasta que el pilotaje alcanza los 2,5 bar. Cuatro mil pasos de integración numérica, no una fórmula de sobremesa. Y el resultado depende de la red: bajar de 6 a 5 bar alarga el retardo un 17,0 %, y el segundo bar cuesta más que el primero (+21,9 % adicional). Por eso el criterio no es «que dé el tiempo», sino «que lo siga dando con la red caída»: robustez, evaluada como criterio aparte.

El último criterio es el que menos se enseña y el que más se paga en planta: la repetibilidad. Un estrangulador casi cerrado da el tiempo que pidas, pero con k por debajo de 0,15 la posición del tornillo deja de ser repetible y el mismo ajuste da tiempos distintos cada mañana. Ajustar «a ojo hasta que salga» es exactamente el error que el banco califica como fallo. Motor verificado 181/181.`,
  conceptos: [
    { icono: '🔗', nombre: 'La lógica neumática es analógica', descripcion: 'La válvula de simultaneidad entrega min(p1, p2) y la selectora entrega max(p1, p2); no hay umbral interno que «limpie» la señal. El 1 lógico vale lo que valga la peor entrada, y sólo es un 1 de verdad si supera los 2,5 bar de pilotaje. Por eso una entrada regulada a 2 bar bloquea una función Y con todo el circuito sano — el bloqueo no es una avería, es aritmética.' },
    { icono: '🧩', nombre: 'Comprar el componente justo (o ninguno)', descripcion: 'Cinco montajes para dos funciones: dos 3/2 en serie (Y, 0 componentes), válvula de simultaneidad (Y, 1), relevador de baja presión + simultaneidad (Y, 2), válvula selectora (O, 1) y empalme en T (O, 0 y nunca válido). El coste es un orden de complejidad, no un precio: primero el número de componentes, luego el depósito más pequeño. La serie gana cuando puede; el relevador se compra sólo cuando la simultaneidad no llega al umbral.' },
    { icono: '💨', nombre: 'El empalme en T que «funciona»', descripcion: 'Unir dos líneas en un nodo hace la O aparente, pero abre un camino permanente hacia el escape de la válvula inactiva. El nodo se resuelve por bisección igualando el caudal que entra y el que sale, ambos con ISO 6358. Resultado: presión degradada, distinta según qué entrada se pulse, y una fuga continua medida en l/min, m³ por turno y kWh. En la puerta de horno la asimetría es brutal: 1,00 bar desde el panel frente a 5,85 desde el pedal.' },
    { icono: '⏱️', nombre: 'El retardo se integra, no se elige', descripcion: 'Depósito + estrangulador llenados según ISO 6358 con b = 0,45: rama sónica Q = C·p1 y rama subsónica con la elipse, integradas en 4000 pasos hasta los 2,5 bar de pilotaje. El tiempo escala con el volumen y con la apertura, y se alarga un 17,0 % al perder un bar de red (21,9 % en la estación de 5 bar). Dos criterios separan lo que funciona de lo que dura: robustez frente a la caída de red y repetibilidad con k ≥ 0,15.' },
  ],
  mision: [
    'LÓGICA · Recorre los cinco montajes en la estación de encolado y mira la fila de presión de salida. La serie no existe ahí (una entrada es una señal ya generada, no un órgano). La simultaneidad entrega min(6; 2) = 2,00 bar y la válvula de potencia, que pide 2,5, no se mueve: todo sano y la máquina parada. El relevador de baja presión dispara a 1,2 y repone 6,00 bar — dos componentes, pero es el único que funciona. Luego vete a la prensa de embutido y comprueba lo contrario: ahí la serie da los 6,00 bar con CERO componentes y la simultaneidad es dinero tirado.',
    'FUGA · Monta el empalme en T en la puerta de horno y lee el nodo. Desde el pedal salen 5,85 bar y la puerta abre; desde el pulsador del panel salen 1,00 bar y no abre — el síntoma clásico de «funciona con un botón y con el otro no». Por el nodo se van 149 l/min hacia el escape de la válvula que no pulsaste: 71,5 m³ por turno, 7,9 kWh. Recorre las otras cuatro estaciones y verás que el T casi siempre «funciona» (4,52 bar en tres de ellas) y NUNCA es válido: por eso se monta tanto y por eso se paga tanto.',
    'TIEMPO · Barre la matriz depósito × apertura de la estación de encolado, que pide entre 14 y 30 s. Con 100 cm³ no llegas ni cerrando: 15,28 s a la apertura mínima, y ahí el estrangulador ya está por debajo de k = 0,15 y deja de ser repetible. Con 250 cm³ y k = 0,25 salen 15,281 s, y con la red caída un bar suben a 17,877 — dentro de la ventana. Compara con la cabina de pintura, que trabaja a 5 bar: allí el mismo bar perdido cuesta un 21,9 % en vez de un 17,0 %, porque cuanto más baja la red, más caro sale cada bar.',
    'RETO · Se sortea una estación y proyectas el mando completo: elemento lógico, depósito y apertura del estrangulador, tres decisiones independientes calificadas por separado con las otras dos ya correctas. Las 875 combinaciones (5 estaciones × 5 elementos × 5 depósitos × 7 aperturas) se barrieron una a una: hay exactamente UNA terna válida y de coste mínimo en cada estación, y cada uno de los siete criterios puede fallar él solo en alguna combinación —función 36 veces, topología 9, presión 6, fuga 2, ventana de tiempo 58, robustez 10 y repetibilidad 2—. Cumplir no basta: montar una simultaneidad donde bastan dos 3/2 en serie también es equivocarse.',
  ],
  aplicaciones: [
    { area: 'Diagnóstico de máquinas neumáticas paradas sin avería', ejemplo: 'La llamada más frecuente del taller es «la máquina no arranca y no encuentro nada roto». En lógica neumática eso tiene una causa numérica: la función Y entrega el mínimo de sus entradas, así que basta con que una de ellas venga de una rama regulada, de un tubo largo o de un manómetro mal ajustado para que la salida caiga por debajo del pilotaje. El técnico que sabe esto no cambia la válvula: mide las dos entradas, compara con el umbral y decide si hay que reponer presión con un relevador o subir la rama débil. El mismo razonamiento explica el fallo hermano —«arranca con un botón pero no con el otro»— que casi siempre es un empalme en T haciendo de selectora.' },
    { area: 'Auditoría de aire comprimido y coste energético', ejemplo: 'El aire comprimido es la energía más cara de una planta y las fugas de circuito lógico son invisibles porque no silban: se van por el escape de una válvula que está haciendo su trabajo. Un solo empalme en T mal montado deja pasar del orden de 100 a 150 l/min de forma continua mientras el operario mantiene pulsado, lo que en un turno de ocho horas son decenas de metros cúbicos y varios kWh. Poner número a esa fuga —caudal, volumen por turno y energía— convierte una discusión de opiniones en una orden de compra de una válvula selectora de dos pesos que se paga sola en semanas.' },
    { area: 'Ajuste de temporizaciones repetibles en producción', ejemplo: 'Un temporizador neumático ajustado «a ojo hasta que salga» es una avería aplazada. El tiempo depende del volumen del depósito, de la apertura del estrangulador y de la presión de red, y las tres cosas se mueven: la red baja en los picos de consumo y el tornillo casi cerrado no vuelve a la misma posición dos veces. El criterio profesional es doble — dimensionar el depósito para que el tiempo pedido caiga con el estrangulador razonablemente abierto (k ≥ 0,15, criterio de fabricante) y comprobar que la ventana se sigue cumpliendo con un bar menos de red. Es la diferencia entre una máquina que funciona el día del arranque y una que funciona en agosto.' },
  ],
};

export default briefing;
