import type { BriefingConfig } from '@/components/MissionBriefing';

const briefing: BriefingConfig = {
  codigo: 'MEC-107',
  titulo: 'Dimensiona un Acumulador Hidroneumático y su Precarga de Nitrógeno',
  subtitulo: 'Hidráulica y Neumática · El acumulador no guarda aceite: guarda nitrógeno, y la precarga tiene ventana por los dos lados',
  acento: '#EFB13A',
  duracion: 45,
  videoUrl: '',
  bienvenida: `Un acumulador hidroneumático no guarda aceite. Guarda NITRÓGENO comprimido, y el aceite sólo es el pistón que lo comprime. Todo lo demás sale de ahí.

De esa frase y de una sola ley: p·Vⁿ = constante, escrita tres veces —en la precarga p₀, en la presión mínima de trabajo p₁ y en la máxima p₂— para saber cuánto aceite sale de verdad. Y la primera sorpresa es que la n importa muchísimo. El mismo cuerpo de 10 L, la misma precarga, el mismo salto de presión: si el ciclo es lento y le da tiempo al gas a soltar calor entrega 3,3538 L; si es rápido y el gas se calienta al comprimirse, 2,6271. Un 21,67 % menos de aceite sin cambiar una pieza. Y ese aceite NO se recupera subiendo la precarga.

Lo segundo es la ventana. La precarga es el único ajuste que se hace con el aparato ya montado, y está acotada por los dos lados a la vez. En la apertura de emergencia de la prensa, con el acumulador de pistón de 5 L, de las SIETE precargas del catálogo sirve exactamente UNA. Por abajo manda el aceite: al 70 % entrega 2,0962 L y el cilindro necesita 2,1058, así que la prensa no abre. Al 75 % entrega 2,2021 y cumple… hoy. Dentro de un año, con el 3 % de nitrógeno que se escapa a través de la vejiga y los 2 bar de tolerancia del kit de carga, se queda en 2,0916 y deja de abrir. Y por arriba manda la temperatura: los 55,80 bar rotulados a 20 °C se convierten en 70,53 a los 55 °C de la nave, y el tope del plato está en 62,90. El separador se queda pegado contra la válvula y el aparato deja de existir.

Eso es lo tercero, y es lo que más suspende de todo el banco: la precarga que se ROTULA no es la que TRABAJA. p₀(T) = p₀,ref·(273,15+T)/(273,15+20). Hay que dimensionar en frío y en caliente a la vez, y de los siete criterios el que tumba más montajes él solo es el tope térmico del plato: 251 veces, con todo lo demás en regla.

Lo cuarto rompe otro reflejo: más gas NO es más aceite. En el sostenimiento de un amarre con la bomba parada, el mismo acumulador de vejiga de 10 L aguanta 3,7382 h sin botellas de transferencia, 7,1963 h con una botella… y 3,8499 h con dos. El óptimo es INTERIOR. A partir de cierto punto las botellas ya no pueden vaciarse de gas, el cuerpo se llena de aceite antes de tiempo y el resto del salto de presión se tira a la basura.

El banco tiene cinco faenas y 1 995 configuraciones (19 modelos × 7 precargas × 3 opciones de botellas × 5 faenas). Siete criterios que hay que cumplir a la vez, y sólo 392 lo consiguen. La función —«¿sale el aceite que hace falta?»— no suspende NUNCA ella sola: cero veces en 1 995. Si no llega hoy, tampoco llega dentro de un año.

Motor verificado con 41 712 comprobaciones numéricas, la transcripción al simulador con 98 705 comparaciones campo a campo, y la simulación con 322 aserciones en navegador real.`,
  conceptos: [
    { icono: '💨', nombre: 'El acumulador guarda gas, no aceite', descripcion: 'ΔV = V₀·p₀^(1/n)·(p₁^(−1/n) − p₂^(−1/n)) sale de aplicar p·Vⁿ = cte tres veces. El volumen que dice el catálogo es el del GAS a precarga, y el aceite que sale de verdad es una fracción de él: el cuerpo de 10 L al 90 % entre 100 y 160 bar entrega 3,3538 L si el ciclo es isotermo y 2,6271 si es adiabático. El índice politrópico no es un adorno: la caída es del 21,67 % y no se compra de vuelta con más precarga. Y el gas tiene DOS topes de carrera —el cuerpo entero por arriba, las botellas de transferencia por abajo— donde la respuesta deja de ser una curva suave; el laboratorio los declara como estado en vez de dibujar un número imposible.' },
    { icono: '🌡️', nombre: 'La precarga que se rotula no es la que trabaja', descripcion: 'p₀(T) = p₀,ref·(273,15+T)/(273,15+20), Gay-Lussac puro, y es el criterio que más montajes tumba en solitario: 251 de 1 995. Los 55,80 bar rotulados a 20 °C de la prensa valen 52,89 a los 5 °C de un arranque de invierno y 70,53 a los 55 °C de la nave en agosto, contra un tope de plato de 0,90·p₁ = 62,90 bar. Por eso la precarga se comprueba SIEMPRE con el aparato a temperatura conocida y con la corrección hecha, y por eso el dato de la chapa lleva la temperatura al lado. Un acumulador precargado bien en enero puede estar fuera de norma en julio sin que nadie lo haya tocado.' },
    { icono: '🪟', nombre: 'La ventana de precarga está cerrada por los dos lados', descripcion: 'Por arriba: el plato en caliente (0,90·p₁) y la relación de compresión p₂/p₀ en frío que el separador aguanta —4 en vejiga, 8 en membrana, 10 en pistón—. Por abajo: el aceite que entrega hoy y el que entregará dentro de un año, con el 3 % de permeación anual del nitrógeno y los 2 bar de tolerancia del kit. En la prensa la ventana se reduce a UNA de las siete precargas: 50, 60 y 70 % no entregan; 75 % entrega hoy pero no a un año; 80 % pasa; 90 y 95 % revientan el plato en caliente. Y en el sostenimiento del amarre pasa lo mismo: una sola precarga y una sola combinación de botellas.' },
    { icono: '⚡', nombre: 'Cuatro problemas distintos, la misma ley del gas', descripcion: 'GOLPE DE ARIETE: celeridad de Korteweg 1 258,1 m/s en tubo de acero Ø50×4 (frente a 1 313,1 en tubo rígido) y pico de Joukowsky Δp = ρ·c·Δv = 27,87 bar → 147,87 bar sin acumulador, por encima del límite de 140; con una vejiga de 1 L que absorbe 664,6 J, 132,03 bar. CIRCUITO SELLADO: 8 L de aceite con β = 7·10⁻⁴ K⁻¹ y 35 K de calentamiento dilatan 0,196 L y llevarían el amarre a 467,5 bar; el mismo litro de vejiga lo deja en 143,2. RIZADO: 3 cm³ por pulso a 72,5 Hz dan 12,87 bar con una membrana de 0,075 L y 2,76 con una de 0,35. VOLUMEN DE EMERGENCIA: 2,1058 L para mover un Ø125/70 con 250 mm de carrera.' },
  ],
  mision: [
    'EL GAS Y SUS DOS TOPES · Modo El gas. Recorre la curva p·Vⁿ del cuerpo de 10 L y localiza los dos límites de carrera: por arriba el cuerpo entero (el gas no puede ocupar más que el aparato) y por abajo las botellas de transferencia (nunca se vacían de gas). Cambia después el índice n sin tocar NADA más: 3,3538 L con n = 1,0 · 2,9489 con n = 1,2 · 2,6271 con n = 1,4. Es el mismo hierro entregando un 21,67 % menos de aceite sólo porque el ciclo va más deprisa. Ese aceite no se recupera con precarga: se recupera con más acumulador o con un ciclo más lento.',
    'LAS CINCO FAENAS · Modo La faena. La misma ley contesta a cinco preguntas distintas: cuánto aceite entrega (emergencia de la prensa, ≥ 2,1058 L), cuánto rizado deja pasar (bomba de tres pistones, ≤ 4 bar), qué pico alcanza un golpe de ariete (≤ 140 bar), a qué presión llega un circuito de amarre sellado que se calienta (≤ 160 bar) y cuánto tiempo sostiene el amarre con la bomba parada (≥ 5 h). Vigila el estado del gas en la telemetría: cuando toca uno de sus topes, el aparato empieza a mentir y el laboratorio lo dice en vez de disimularlo.',
    'LA VENTANA, DE PUNTA A PUNTA · Modo La precarga, faena de emergencia, acumulador de pistón de 5 L, sin botellas. Barre las siete precargas y anota lo que pasa: al 50 % entrega 1,6484 L, al 60 % 1,8777, al 70 % 2,0962 —y el cilindro pide 2,1058, así que por 10 cm³ la prensa no abre—. Al 75 % entrega 2,2021 y cumple, pero mira la fila «a un año»: 2,0916. Suspende. Al 80 % entrega 2,3060 hoy y 2,1944 dentro de un año, y es la ÚNICA que pasa. Al 90 y al 95 %, la telemetría se pone roja arriba: 70,53 y 74,50 bar en caliente contra un plato de 62,90.',
    'EL FRÍO, EL CALOR Y EL AÑO QUE VIENE · Sin salir de La precarga, quédate en el 80 % y lee las cuatro presiones del mismo gas: 55,80 bar rotulados a 20 °C, 52,89 a los 5 °C de un arranque de invierno, 62,58 a los 55 °C de la nave y 49,27 dentro de un año. Son 3,62 bar de deriva —un 3 % de permeación más los 2 bar del kit— y son los que separan un acumulador que abre la prensa de uno que no. Comprueba también la relación de compresión en frío: 4,657 sobre un pistón que admite 10. Con una vejiga, que sólo admite 4, este montaje ya no valdría.',
    'MÁS GAS NO ES MÁS ACEITE · Modo La faena, sostenimiento del amarre, vejiga de 10 L al 80 %. Sin botellas aguanta 3,7382 h y suspende (se piden 5). Con UNA botella de 10 L aguanta 7,1963 h y pasa. Con DOS aguanta 3,8499 h y vuelve a suspender. No es un error: el óptimo es interior. Las botellas no se vacían nunca de gas, así que a partir de cierto punto el cuerpo se llena de aceite antes de llegar a p₂ y el resto del salto de presión no se aprovecha. Ésta es la faena donde más caro sale suponer en vez de calcular.',
    'EL ARIETE Y EL CIRCUITO SELLADO · Sigue en La faena. Golpe de ariete: celeridad de Korteweg 1 258,1 m/s en el tubo de acero Ø50×4 —menos que los 1 313,1 del aceite en un tubo rígido, porque el tubo también se dilata—, velocidad de línea 2,5465 m/s, pico de Joukowsky 27,87 bar sobre los 120 de la línea: 147,87 bar sin acumulador contra un límite de 140. Con una vejiga de 1 L que absorbe los 664,6 J de energía cinética, 132,03. Circuito sellado: 0,196 L de dilatación térmica que no caben en ninguna parte llevarían el amarre a 467,5 bar; el mismo litro de vejiga lo deja en 143,2.',
    'EL CATÁLOGO ENTERO · Modo El catálogo. Diecinueve modelos con la misma faena delante y siete criterios que hay que cumplir a la vez. De las 1 995 configuraciones sólo 392 pasan: 55 · 64 · 73 · 132 · 68 por faena. Mira el censo de fallos en solitario: 251 el plato en caliente, 127 el tiempo de respuesta del separador —los de pistón tardan 100 ms y en el ariete se piden 15—, 40 la relación de compresión, 21 la presión admisible, 17 la deriva, 10 el caudal de paso… y CERO la función. La función nunca suspende sola. Piensa por qué antes de seguir leyendo: porque la deriva sólo empeora, y si no llega hoy tampoco llegará dentro de un año.',
    'RETO · Se sortea una faena y arrancas con los ejes mal a propósito: modelo, precarga y botellas. Cada eje se califica por separado con los otros en su óptimo, así que sabrás cuál fallaste sin que te den la respuesta, y el diagnóstico te dará la cifra y el límite —«a 55 °C la precarga sube a 70,53 bar y el plato aguanta hasta 62,90»— y nunca la solución. Cumplir los siete criterios no basta: hay que montar el válido MÁS BARATO, y a igualdad de coste el que menos gas instala. El óptimo es único en las cinco faenas: pistón de 5 L al 80 % por 33 en la emergencia, membrana de 0,35 L al 75 % por 7 en el rizado, vejiga de 1 L al 80 % por 12 en el ariete y en el circuito térmico, y vejiga de 10 L a 150 bar con una botella por 32 en el sostenimiento.',
  ],
  aplicaciones: [
    { area: 'Dimensionado de un acumulador para una función de emergencia', ejemplo: 'La decisión que en un pliego se toma mirando sólo el volumen del catálogo y que aquí se demuestra que depende de otras cinco cifras. El volumen nominal es el del GAS a precarga, no el del aceite disponible: el cuerpo de 5 L de la prensa entrega 2,3060 L útiles, menos de la mitad. Y la función no es el único criterio: hay que sobrevivir al tope térmico del plato, a la relación de compresión que el separador aguanta en frío, a la presión máxima admisible del cuerpo, al caudal de paso de la conexión, al tiempo de respuesta del separador y a la permeación de un año. El banco pone las siete condiciones sobre la mesa a la vez, barre 1 995 montajes y demuestra que sólo 392 las cumplen todas y que el óptimo de cada faena es único bajo un orden de decisión declarado antes de barrer.' },
    { area: 'Carga y comprobación periódica de la precarga de nitrógeno', ejemplo: 'La operación de mantenimiento más frecuente y peor hecha de una instalación con acumulador. Aquí se ve por qué la lectura del manómetro del kit no significa nada sin la temperatura: los mismos 55,80 bar rotulados a 20 °C son 52,89 a 5 °C y 70,53 a 55 °C, y el tope del plato está en 62,90. Se ve también por qué la comprobación es periódica y no de una sola vez: con un 3 % de permeación anual y los 2 bar de tolerancia del propio kit, un montaje que hoy entrega 2,2021 L entrega 2,0916 dentro de un año y deja de cumplir. Y se ve por qué el procedimiento empieza SIEMPRE por descargar el lado de aceite y aislar el acumulador con el bloque de seguridad que exige la ISO 4413: un acumulador cargado es una máquina con energía almacenada aunque la bomba lleve una semana parada.' },
    { area: 'Amortiguación de golpe de ariete, rizado y dilatación térmica', ejemplo: 'Tres problemas que en el taller se diagnostican como «vibración», «ruido» o «la máquina se pone dura sola» y que tienen aquí su mecanismo con números. El ariete se calcula con la celeridad real de la onda —Korteweg, 1 258,1 m/s, no la del fluido libre— y el pico de Joukowsky ρ·c·Δv; un cierre en 40 ms sobre una línea cuyo tiempo de ida y vuelta 2L/c es de 190,8 ms es un cierre RÁPIDO y el pico sale entero. El rizado de una bomba de pistones se ataca con el volumen de gas que ve cada pulso, y el circuito de amarre sellado que se calienta necesita sitio donde meter la dilatación del aceite o llega a 467,5 bar y revienta por donde menos conviene. Las tres se resuelven con el mismo aparato y la misma ley, y las tres tienen precarga óptima distinta. El paso siguiente —pérdidas de carga tramo a tramo por Darcy–Weisbach y selección de conducciones— es materia de la práctica d4-A2.' },
  ],
};

export default briefing;
