import type { BriefingConfig } from '@/components/MissionBriefing';

const briefing: BriefingConfig = {
  codigo: 'MEC-82',
  titulo: 'Máquinas de Estados Finitos · Moore / Mealy',
  subtitulo: 'Sistemas Digitales · Lógica secuencial · Diagrama de estados, detector de secuencia y controlador de proceso',
  acento: '#8AB4F8',
  duracion: 30,
  videoUrl: '',
  bienvenida: `Un ascensor que recuerda a qué piso lo llamaron, un semáforo que recorre sus fases en orden, un lector que espera una secuencia exacta de bits antes de abrir una puerta: todos son la misma idea de ingeniería, la MÁQUINA DE ESTADOS FINITOS (FSM). Es el patrón con el que se diseña casi toda la lógica secuencial —desde dos flip-flops y unas compuertas hasta el programa de un PLC— y este laboratorio te lleva de la idea al circuito pasando por su herramienta central: el diagrama de estados.

Una FSM es un circuito secuencial que en cada flanco de reloj pasa de un ESTADO a otro según su ENTRADA y produce una SALIDA. El estado es la MEMORIA de la máquina: resume todo el pasado que importa para decidir el futuro, así que basta un puñado de estados para gobernar un proceso complejo. Hay dos estilos, y la diferencia es exactamente dónde nace la salida. En una máquina de MOORE la salida depende SÓLO del estado: es estable y "registrada" (aparece un ciclo después de la entrada que la provocó) y por eso es ideal para accionar actuadores sin glitches, aunque suele necesitar un estado más. En una de MEALY la salida depende del ESTADO Y de la ENTRADA actual: reacciona en el mismo ciclo y ahorra un estado, a cambio de poder glitchear con la entrada. Ambas se especifican con el mismo par de herramientas: el DIAGRAMA de estados (los círculos y las flechas) y la TABLA de estados (estado actual → señal → estado siguiente, y la salida de cada estado). Esa tabla es el puente literal hacia el circuito —dos flip-flops para cuatro estados más lógica combinacional— o hacia el código —una variable de estado y un bloque CASE por etapa en un PLC.

Verás la FSM en dos usos reales. Primero, un DETECTOR DE SECUENCIA que reconoce un patrón de bits permitiendo SOLAPE: al fallar un bit no siempre vuelve a cero, sino al prefijo útil más largo (la failure-function de KMP), y lo construimos en forma de Moore (len+1 estados) y de Mealy (len estados) comprobando que reconocen exactamente las mismas posiciones. Segundo, un CONTROLADOR DE PROCESO INDUSTRIAL de Moore: un tanque de mezcla de cuatro etapas ESPERA→LLENADO→MEZCLA→VACIADO que se RETIENE en cada etapa (self-loop) hasta que llega su señal —arranque, nivel alto, tiempo cumplido, nivel bajo— y cuyos actuadores dependen sólo del estado. Todo el comportamiento se verificó numéricamente: 6 patrones × 3 flujos comparados con fuerza bruta, la equivalencia Moore↔Mealy y su relación de tiempos, y un barrido 4×16 del proceso confirmando determinismo, retención y salidas por estado — 14/14.`,
  conceptos: [
    { icono: '🧠', nombre: 'Estado = memoria', descripcion: 'Una FSM es un circuito secuencial que en cada flanco de reloj pasa de un estado a otro según su entrada y emite una salida. El estado resume todo el pasado que importa: con unos pocos estados se gobierna un proceso complejo. Cuatro estados caben en dos flip-flops (2ⁿ estados con n biestables).' },
    { icono: '⏱️', nombre: 'Moore vs Mealy', descripcion: 'En Moore la salida depende SÓLO del estado: estable, registrada (un ciclo después) y glitch-free, ideal para actuadores, pero suele usar un estado más. En Mealy la salida depende del estado Y de la entrada: reacciona el mismo ciclo y ahorra un estado, a costa de posibles glitches. La salida Moore = la Mealy registrada un ciclo.' },
    { icono: '🔎', nombre: 'Detector de secuencia (con solape)', descripcion: 'Reconoce un patrón de bits dentro de un flujo. La clave es que un bit incorrecto no siempre reinicia a cero: retrocede al prefijo útil más largo (failure-function de KMP), lo que permite solape (101 aparece dos veces en 10101). Se construye igual en Moore (len+1 estados) y Mealy (len estados) y detecta las mismas posiciones.' },
    { icono: '🏭', nombre: 'Controlador de proceso (Moore)', descripcion: 'Un secuenciador industrial es una FSM de Moore: cada etapa es un estado que se RETIENE (self-loop) hasta que llega su señal (nivel, tiempo, sensor) y sus actuadores dependen sólo del estado. El tanque de mezcla ESPERA→LLENADO→MEZCLA→VACIADO ilustra el patrón de semáforos, prensas, lavadoras y PLC.' },
  ],
  mision: [
    'EXPLORA · Conduce una FSM en vivo. En el DETECTOR, elige un patrón y alimenta bits de uno en uno: verás el estado avanzar en el diagrama y, al fallar, retroceder al prefijo útil (no siempre a cero), por eso hay solape; cambia entre Moore y Mealy y comprueba que detectan las mismas posiciones. En el PROCESO, da la señal de avance para recorrer el ciclo del tanque y pulsa una señal irrelevante para ver que la etapa se RETIENE (self-loop) hasta que llega su sensor.',
    'APLICA · Compara y formaliza. En "Moore vs Mealy" lee el diagrama de tiempos: la salida Mealy sube en el ciclo del bit que completa el patrón y la Moore, la misma detección, un ciclo después (registrada); confirma que Moore usa un estado más y que ambos reconocen el mismo lenguaje. En "Tabla del proceso" recorre la tabla de estados completa (estado → señal → siguiente → actuadores): de ahí salen las ecuaciones de los flip-flops o el CASE del PLC.',
    'RETO · Diseña la FSM de un proceso industrial (embotelladora, lavadora, prensa o semáforo). Para cada etapa elige a qué etapa AVANZA cuando llega su señal y qué ACTUADOR enciende. El ciclo correcto recorre las cuatro etapas en orden y vuelve al inicio (sin saltar ni estancar ninguna) y cada etapa acciona su propio actuador (Moore). El sistema califica por separado la tabla de transición y la de salidas: es un reto de diseño, sin valor oculto que adivinar.',
  ],
  aplicaciones: [
    { area: 'Control industrial y secuenciadores (PLC)', ejemplo: 'Casi todo automatismo es una FSM de Moore: un semáforo recorre verde→amarillo→rojo por temporizador; una lavadora encadena llenado→lavado→enjuague→centrifugado; una prensa neumática baja, prensa y sube. En un PLC se programa como una variable de estado y un bloque CASE por etapa, con self-loops que retienen cada paso hasta que su sensor (nivel, presión, fin de carrera) lo libera.' },
    { area: 'Protocolos y detección de secuencias', ejemplo: 'La recepción de una trama serie, el reconocimiento de un preámbulo o un código de acceso, y el descarte de bits de relleno se implementan como detectores de secuencia. La failure-function (KMP) permite reconocer patrones con solape sin reprocesar bits, y variantes de la misma idea sostienen los autómatas que analizan protocolos, expresiones y flujos de datos a alta velocidad.' },
    { area: 'Controladores digitales en HDL (FPGA/ASIC)', ejemplo: 'El "control path" de casi cualquier bloque digital —el controlador de una memoria, un árbitro de bus, la unidad de control de un procesador sencillo— se describe como una FSM en Verilog o VHDL. Elegir Moore o Mealy es una decisión de temporización real (salida registrada glitch-free frente a un ciclo de latencia menos), y el diagrama de estados es el documento de diseño que se sintetiza a flip-flops.' },
  ],
};

export default briefing;
