import type { CatalogoEntry } from '../_types';

const catalogo: CatalogoEntry = {
  modulo: "Sistemas Digitales",
  titulo: "Máquinas de Estados Finitos · Moore / Mealy",
  duracion: "30 min",
  teoria: "Una MÁQUINA DE ESTADOS FINITOS (FSM) es un circuito secuencial que en cada flanco de reloj pasa de un ESTADO a otro según su ENTRADA y produce una SALIDA; el estado es la MEMORIA de la máquina, pues resume todo el pasado que importa para decidir el futuro (n flip-flops codifican hasta 2ⁿ estados). Hay dos estilos según dónde nace la salida. En una máquina de MOORE la salida depende SÓLO del estado: es estable y registrada (aparece un ciclo después de la entrada que la provoca) y por eso es ideal para actuadores sin glitches, aunque suele necesitar un estado más. En una de MEALY la salida depende del ESTADO Y de la ENTRADA actual: reacciona en el mismo ciclo y ahorra un estado, a cambio de posibles glitches con la entrada. Ambas se especifican con el DIAGRAMA de estados (círculos y flechas) y la TABLA de estados (estado actual → señal → estado siguiente, y la salida de cada estado), que son el puente hacia el circuito (dos flip-flops para cuatro estados más lógica combinacional) o hacia el programa de un PLC (una variable de estado y un bloque CASE por etapa). El laboratorio muestra la FSM en dos usos reales. Un DETECTOR DE SECUENCIA reconoce un patrón de bits permitiendo SOLAPE: al fallar un bit no siempre reinicia a cero, sino que retrocede al prefijo útil más largo mediante la failure-function de KMP (así 101 se detecta dos veces en 10101); se construye en forma de Moore (estados 0..len, salida = estado de aceptación) y de Mealy (estados 0..len-1, salida en el bit que completa el patrón), y ambos reconocen las mismas posiciones, verificado contra fuerza bruta. Un CONTROLADOR DE PROCESO INDUSTRIAL de Moore modela un tanque de mezcla de cuatro etapas ESPERA→LLENADO→MEZCLA→VACIADO que se RETIENE en cada etapa por self-loop hasta que llega su señal (arranque, nivel alto, tiempo cumplido, nivel bajo) y cuyos actuadores (válvula de entrada, bomba, motor de mezcla, válvula de drenaje) dependen sólo del estado. Relaciones clave: la salida de Moore es la de Mealy registrada un ciclo después, y para un detector de longitud len, Moore usa len+1 estados y Mealy len. Todo se verificó numéricamente de forma exhaustiva (6 patrones × 3 flujos comparados con fuerza bruta, solape 101 en 10101 → [2,4], conteo de estados, equivalencia de lenguaje y relación de tiempos, y barrido 4×16 del proceso confirmando determinismo, retención y salidas por estado — 14/14). No modela tiempos reales (setup/hold, retardo reloj-a-Q, metaestabilidad), glitches concretos de Mealy, minimización/codificación de estados ni la síntesis física. Referencias: Mano & Ciletti (Diseño Digital), Wakerly (Digital Design), Roth & Kinney (Fundamentals of Logic Design), Katz & Borriello (Contemporary Logic Design) y Knuth-Morris-Pratt (Fast Pattern Matching in Strings, 1977).",
  estado: "activo",
  simuladorHtml: "/labs/maquinas-estado.html",
};

export default catalogo;
