import type { BriefingConfig } from '@/components/MissionBriefing';

const briefing: BriefingConfig = {
  codigo: 'MEC-87',
  titulo: 'Lazo 4–20 mA: Escalado y Control On/Off con Histéresis',
  subtitulo: 'Sistemas Digitales · Instrumentación y señales analógicas · NAMUR NE 43 + IEC 60381-1: cero vivo, cumplimiento de tensión y banda muerta',
  acento: '#8AB4F8',
  duracion: 30,
  videoUrl: '',
  bienvenida: `Un transmisor de nivel no envía metros: envía CORRIENTE. Y la envía por los mismos dos hilos que lo alimentan, en un lazo en serie donde la corriente es la misma en todo el recorrido. Esa es la razón de que la señal de campo sea corriente y no tensión: la caída del cable no falsea la lectura, sólo consume margen. El escalado es una recta, i = 4 + 16·(PV − LRV)/(URV − LRV), y el cero se pone en 4 mA —no en 0— precisamente para poder distinguir «el proceso está en el mínimo» de «el lazo está cortado». Eso es el CERO VIVO, y es lo único que separa una medida de un silencio.

La NAMUR NE 43 convierte esa idea en convención: la medida vive entre 3,8 y 20,5 mA; por debajo de 3,6 y por encima de 21,0 mA el transmisor está declarando una AVERÍA; y entre medias quedan dos zonas —bajo rango y sobre rango— que NO son averías: el aparato sigue midiendo y avisa de que el proceso se salió del rango calibrado. Confundir esas zonas con una avería es lo que hace que se sustituyan transmisores sanos.

De ahí salen los cuatro errores que esta práctica MIDE en lugar de contarlos. Uno: escalar con un rango que no cubre el recorrido del proceso —o que lo cubre con tanta holgura que el 0,5 % de span del transmisor se convierte en centímetros de incertidumbre—. Dos: dimensionar el cable contra 20,0 mA en vez de contra 20,5, que es el error más caro del tema, porque la lectura se queda clavada exactamente cuando el proceso se sale de rango, que es cuando más falta hace; con 24 V y 12 V de tensión mínima en el transmisor, R_máx pasa de 600 Ω a 585,4 Ω, y esos 14,6 Ω son el cable que ya está tendido. Tres: corregir un error de calibración por el lado equivocado, sin ver que el cero DESPLAZA la recta y el span la INCLINA, y que por eso el ajuste de dos puntos va primero cero y después span —al revés deja residuo—. Y cuatro: elegir una banda muerta que hace que la bomba arranque cada dos minutos.

Ese último tiene una trampa que casi nadie ve a la primera: el peor caso de arranques por hora NO es el caudal de entrada máximo, sino el caudal MITAD del de la bomba. El periodo del ciclo es proporcional a 1/q_in + 1/(q_out − q_in), y ese término es mínimo justo en q_in = q_out/2. Quien dimensiona en el caudal máximo deja el arrancador desprotegido en su condición más exigente. Todo se mide sobre un tanque simulado 6,5 h a paso de 1 s, con un motor verificado numéricamente 183/183 —incluido el barrido de las 64 combinaciones de rango, calibre y banda muerta que demuestra que la solución del reto es única—.`,
  conceptos: [
    { icono: '🔌', nombre: 'Cero vivo y lazo de dos hilos', descripcion: 'El transmisor se alimenta y transmite por los mismos dos conductores, y la corriente es idéntica en todo el lazo serie: por eso la resistencia del cable no falsea la medida. El mínimo está en 4 mA y no en 0 para que «proceso en el mínimo» y «lazo cortado» no se lean igual. Un 0–20 mA no puede distinguirlos.' },
    { icono: '🚦', nombre: 'NAMUR NE 43', descripcion: 'Medida válida entre 3,8 y 20,5 mA; avería en ≤ 3,6 y ≥ 21,0 mA. Entre ambas quedan bajo rango y sobre rango, que NO son averías: el transmisor sigue midiendo y avisa de que el proceso se salió del rango calibrado. La dirección de la avería es configurable según lo que sea seguro en ese proceso.' },
    { icono: '⚡', nombre: 'Cumplimiento de tensión', descripcion: 'i_máx = (V_alim − V_tx,mín)/R_total, con R_total = R_medida + 2·ρ(AWG)·L + R_extra. El lazo hay que dimensionarlo contra 20,5 mA, no contra 20,0: con 24 V y V_tx,mín = 12 V eso baja el techo de 600 Ω a 585,4 Ω. Si no se sostiene, la lectura satura justo cuando el proceso se sale de rango.' },
    { icono: '🔁', nombre: 'Banda muerta y peor caso', descripcion: 'Sin histéresis el contactor traquetea; con histéresis el nivel oscila. La banda muerta se elige por vida útil del arrancador y después se comprueba contra la tolerancia del proceso. Y su peor caso está en q_in = q_out/2, no en el caudal máximo: arranques máx/h = 15·q_out/(DB·A·1000).' },
  ],
  mision: [
    'EXPLORA · Mueve el nivel por su recorrido y observa a la vez el diagrama del lazo —fuente de 24 V, transmisor de dos hilos y resistencia de medida—, la recta de escalado con la banda NE 43 sombreada, la regla de corriente con sus cinco zonas y la tabla de cinco puntos del rango. Después inyecta las averías: hilo roto (0 mA), falla baja (3,6), falla alta (21,0), bajo rango (3,7) y sobre rango (20,8), y comprueba cómo cambia la clasificación y qué nivel deduciría el sistema de control en cada caso —incluido el nivel absurdo que deduciría si tratase una señal de avería como si fuese medida—.',
    'APLICA · Tres estudios. En "Escalado" se inyecta un error de cero, uno de span o los dos, y el ajuste de dos puntos se CALCULA sobre ese error: las tablas de cinco puntos antes y después muestran el residuo y por qué el orden del ajuste no es opcional. En "Lazo" aparece el presupuesto de tensión en barras —cuánto se lleva la resistencia de medida, cuánto el cable y cuánto le queda al transmisor—, la tabla de los cuatro calibres con su corriente máxima y la curva de saturación. En "Histéresis" se simulan noventa minutos de tanque con nivel real, nivel leído y bandas de bomba, y las cuatro bandas muertas se comparan por arranques/hora en el peor caso y por oscilación resultante.',
    'RETO · Dimensiona una instalación asignada en tres decisiones independientes: el rango del transmisor, el calibre del par y la banda muerta del control. Cada criterio se evalúa con los otros dos ya correctos, así que acertar dos de tres sigue siendo una instalación que no funciona. Las 64 combinaciones (4 rangos × 4 calibres × 4 bandas) se barrieron una a una en cada instalación: hay exactamente una válida. El dimensionado de partida está deliberadamente mal en las tres, y el calibre viene subdimensionado a propósito.',
  ],
  aplicaciones: [
    { area: 'Instrumentación de proceso y estaciones de bombeo', ejemplo: 'Nivel en cisternas y pozos, presión en colectores, caudal en líneas de trasiego: el 4–20 mA sigue siendo la señal analógica de campo más extendida precisamente porque sobrevive a cables largos y a entornos ruidosos. Dimensionar bien el par y el rango es lo que separa una instalación que se pone en marcha del tirón de otra que hay que rehacer con el cable ya tendido en la canalización.' },
    { area: 'Diagnóstico de lazos en planta', ejemplo: 'Una lectura clavada en 18 mA cuando el proceso sigue subiendo no es un sensor averiado: es un lazo que se quedó sin tensión, y se confirma midiendo la caída en la resistencia de medida y sumando la del cable. Saber leer las bandas de la NE 43 evita las dos equivocaciones caras del turno de mantenimiento: sustituir un transmisor sano que sólo estaba en sobre rango, y dar por buena una medida que en realidad es una señal de avería.' },
    { area: 'Control todo-nada y vida útil del arrancador', ejemplo: 'Bombas de achique, compresores, resistencias de calentamiento y ventiladores se gobiernan todavía con lógica todo-nada, y el fabricante del arrancador pone un límite de arranques por hora. La banda muerta es el parámetro que respeta ese límite, y el criterio para elegirla —peor caso en el caudal mitad, no en el máximo— conecta esta práctica con la maniobra de motores de MEC-50 y con los temporizadores y contadores IEC de MEC-84.' },
  ],
};

export default briefing;
