import type { BriefingConfig } from '@/components/MissionBriefing';

const briefing: BriefingConfig = {
  codigo: 'MEC-88',
  titulo: 'GPIO: Antirrebote e Interrupciones en un Microcontrolador',
  subtitulo: 'Sistemas Digitales · Entradas digitales y microcontroladores · Umbrales CMOS + 74HC14 + IEC 60947-5-1: polarización, ventana de estabilidad y estrategia de adquisición',
  acento: '#8AB4F8',
  duracion: 30,
  videoUrl: '',
  bienvenida: `Un contacto mecánico no se cierra: REBOTA. Durante unos milisegundos abre y cierra decenas de veces, y un microcontrolador que muestrea cada pocos microsegundos ve cada uno de esos rebotes como una pulsación distinta. Pero antes de llegar ahí hay un problema más básico y peor: un pin de entrada en el aire no vale 0 ni 1, FLOTA. El contacto sólo puede llevar el nodo a un nivel; al otro lo tiene que llevar una resistencia. Un pin sin polarizar funciona en el banco, con el cable de diez centímetros y el laboratorio en silencio, y falla en la máquina: es el error que más veces sobrevive a las pruebas.

Por eso esta práctica tiene tres decisiones encadenadas y no una. Cómo se ACONDICIONA la entrada —flotante, pull-up interno del MCU, pull-up externo de 4,7 kΩ, o filtro RC con disparador Schmitt—, cuánto dura la VENTANA de estabilidad del antirrebote, y con qué ESTRATEGIA se adquiere: sondeo en el lazo principal, sondeo por temporizador, interrupción cruda o interrupción con antirrebote. Cada una se equivoca por una razón distinta y ninguna se puede elegir sin las otras dos.

Hay cuatro cosas que aquí se miden en lugar de contarse. Primera: la hoja de datos da el pull-up interno como un RANGO, 20 a 50 kΩ, y hacen falta los dos extremos —el bajo para la corriente que consume, el alto para el nivel que garantiza—; usar un valor «típico» intermedio es diseñar para un chip que no existe. Segunda: un filtro RC NO es un antirrebote. Con τ_carga = R₁C = 1 ms, un tren de rebotes de 60 ms sale igual de sucio; lo único que cambia es que los flancos son limpios y que la impedancia del nodo baja de 50 kΩ a 398 Ω, que es exactamente lo que hace falta cuando pasa cerca el cable de un variador, porque el ruido no se acopla por resistencia sino por capacidad y lo que decide cuánta tensión genera es Z = R/√(1+(ωRC)²). Tercera: la corriente de HUMECTACIÓN. Un contacto de plata necesita del orden de 1 mA para atravesar su propia película de sulfuro, y un pull-up interno de 20 kΩ da 0,25 mA: el montaje funciona el día de la puesta en marcha y falla seis meses después. Y cuarta, el consumo: con una batería de 2700 mAh el pull-up interno dura 450 días, el filtro RC 248 y el externo de 4,7 kΩ apenas 106.

La regla que ordena la ventana es t_est > t_reb/2, y no se enuncia: se MIDE. Dentro de un tren de rebotes, el par de tramos contiguos más largo suma como mucho t_reb, así que ninguna ventana mayor que su mitad puede quedar atrapada entre dos rebotes; el barrido sobre los trenes generados da exactamente t_reb/2 en las cuatro estaciones. Y ojo con la conclusión fácil: una ventana MÁS LARGA no es más segura. Pasado el techo, el antirrebote se traga pulsaciones enteras o huecos enteros, y en cada instalación ese techo lo pone algo distinto —el hueco de rearme, la anchura del pulso o la separación entre dos pulsaciones seguidas—. Todo corre sobre un motor verificado numéricamente 291/291, incluido el barrido de las 64 combinaciones de acondicionamiento, ventana y estrategia que demuestra que la solución del reto es única en cada instalación.`,
  conceptos: [
    { icono: '🔌', nombre: 'Polarización de la entrada', descripcion: 'El contacto sólo lleva el nodo a un nivel; al otro lo lleva una resistencia. Su valor fija a la vez el consumo (i = Vcc/R_pu), la inmunidad al ruido, la tolerancia a fugas del bornero y la corriente que limpia el contacto. Un pin flotante no tiene dos estados sino tres, y el tercero no aparece en el diagrama lógico.' },
    { icono: '📉', nombre: 'Umbrales y disparador Schmitt', descripcion: 'Con Vcc = 5 V, V_IH = 0,6·Vcc = 3,0 V y V_IL = 0,3·Vcc = 1,5 V; entre ambos la entrada no está definida. El 74HC14 añade histéresis —V_T+ = 2,9 V y V_T− = 2,0 V— y con ella impide que una rampa lenta genere múltiples transiciones. Sus dos constantes de tiempo, τ_carga = 1000 µs y τ_descarga = 90,9 µs, dejan 674 µs de hueco muerto.' },
    { icono: '⏱️', nombre: 'Ventana de estabilidad t_est', descripcion: 'El piso es t_reb/2 y se mide sobre el propio tren de rebotes, no se supone. Pero es un piso, no un objetivo: pasado el techo el antirrebote se traga pulsaciones o huecos enteros. El rango válido es un intervalo cerrado por los dos lados y distinto en cada instalación.' },
    { icono: '⚡', nombre: 'Estrategia de adquisición', descripcion: 'Sondeo en el lazo, sondeo por temporizador, interrupción cruda o interrupción con antirrebote. Las interrupciones no son la opción por defecto sino un recurso escaso: 2 pines externos no atienden 6 entradas, y si el PWM ocupa el temporizador tampoco queda sondeo periódico. Una interrupción sin antirrebote cuenta cada rebote como un evento.' },
  ],
  mision: [
    'EXPLORA · Elige una estación —contador de piezas con reed de plata, final de carrera con microswitch de oro, botón a pilas o selector junto a un variador—, un acondicionamiento y un evento crítico, y observa a la vez tres carriles: la señal cruda del contacto, la que llega al pin y los eventos que el programa acaba contando. Cambiar de acondicionamiento cambia el carril del medio —el flotante deja pasar el ruido, el filtro suaviza los flancos— y ninguno de los dos borra el rebote. La tabla da, de cada acondicionamiento, su corriente en reposo, su impedancia frente al ruido, la tensión de reposo con la fuga real de esa estación y si sirve allí o no.',
    'APLICA · Cuatro estudios. "Acondicionamiento" enfrenta los cuatro montajes en sus cuatro criterios —nivel con fuga, ruido acoplado, humectación y consumo— y traduce el consumo a días de una batería de 2700 mAh. "Filtro RC" dibuja la curva analítica del nodo con los umbrales del Schmitt encima y la misma pulsación con y sin filtro, para ver que 1 ms de τ no borra 60 ms de rebote. "Ventana" muestra el barrido MEDIDO de t_est en 48 puntos logarítmicos entre 100 µs y 200 ms, con la banda válida sombreada y la marca de t_reb/2: por debajo aparecen duplicados y por encima, pérdidas. "Estrategia" dibuja los puntos de muestreo de las cuatro formas de leer la entrada sobre la misma señal.',
    'RETO · Diseña el nodo entero de una instalación asignada en tres decisiones independientes: acondicionamiento, ventana de estabilidad y estrategia de adquisición. Cada criterio se califica con los otros dos ya correctos, así que acertar dos de tres sigue siendo un nodo que no funciona. Las 64 combinaciones (4 acondicionamientos × 4 ventanas × 4 estrategias) se barrieron una a una en cada instalación: hay exactamente una válida. La configuración de partida está deliberadamente mal en las tres.',
  ],
  aplicaciones: [
    { area: 'Máquinas con finales de carrera y detectores', ejemplo: 'Cada final de carrera, cada seta de emergencia y cada detector de posición entra por un pin de un autómata o de una tarjeta con microcontrolador, y todos rebotan. El conteo de piezas que se dispara solo, el ciclo que arranca dos veces con una sola pulsación y la máquina que «funcionaba en el taller» son el mismo problema visto desde tres sitios: polarización, ventana y estrategia mal elegidas.' },
    { area: 'Diagnóstico de entradas en planta', ejemplo: 'Una entrada que marca activa sin que nadie la pulse casi nunca es un pin quemado: suele ser una fuga de bornero de decenas de kΩ hundiendo el reposo de un pull-up interno por debajo de V_IH, y se confirma midiendo la tensión del nodo en reposo, no la continuidad del contacto. Y si el fallo aparece justo cuando arranca el variador, lo que hay que bajar no es la resistencia sino la impedancia del nodo a la frecuencia del ruido.' },
    { area: 'Nodos a batería y mantenimiento', ejemplo: 'En sensores y mandos alimentados por pila, la resistencia de polarización es el consumo dominante en reposo, y elegir la eléctricamente «buena» puede cuadruplicar el coste de mantenimiento: 106 días frente a 450 con la misma batería. Aquí la decisión de diseño se toma con el material del contacto delante —la plata necesita humectación, el oro admite circuito seco—, y conecta con los temporizadores y contadores IEC de MEC-84 y con la maniobra de MEC-85.' },
  ],
};

export default briefing;
