import type { CatalogoEntry } from '../_types';

const catalogo: CatalogoEntry = {
  modulo: "Hidráulica y Neumática",
  titulo: "Calcula Pérdidas de Carga y Selecciona Conducciones",
  duracion: "45 min",
  teoria: "Una conducción no se elige por lo que cuesta el metro, sino por lo que cuesta empujar aceite dentro de ella durante cinco años. El laboratorio pone sobre la mesa 19 conducciones —tubo rígido de acero, manguera de dos trenzas y manguera de espiral—, 3 trazados y 3 líneas en paralelo para cinco faenas de una central hidráulica: 855 montajes posibles, de los que sólo 192 pasan los siete criterios (17 en aspiración, 28 en presión, 42 en retorno, 86 en drenaje y 19 en la línea larga). El cálculo es Darcy–Weisbach de principio a fin, Δp = f·(L_eq/D)·ρv²/2, con f = 64/Re mientras Re < 2 000 y Colebrook–White resuelto por punto fijo por encima de 4 000; Swamee–Jain aparece al lado sólo para que se vea cuánto se aparta la fórmula explícita de la implícita. Lo primero que descubre el alumno es que la longitud que importa no es la que mide la cinta: en aspiración, el trazado directo de la manguera de espiral DN38 recorre 1,80 m reales pero arrastra 88 diámetros de accesorios, es decir 3,353 m equivalentes —el 65,1 % de los 5,153 m totales—; el trazado compacto acorta la manguera a 1,44 m y dispara el conjunto a 15,461 m equivalentes, 10,31 m más de pérdida por ahorrar 36 cm de tubo. Lo segundo es que la viscosidad manda: la misma línea larga de tubo 35×5 pierde 0,6018 bar a 50 °C y 18,1492 bar a −5 °C, porque ν pasa de 29,97 a 903,97 cSt y el Reynolds se desploma de 1 274 a 42; la pérdida se multiplica exactamente por 30,2, el mismo factor que la viscosidad, porque en régimen laminar Δp es proporcional a ν. Lo tercero es que el golpe de ariete no es un añadido: la celeridad de Korteweg vale 1 273 m/s en tubo 22×2 —frente a los 1 313 m/s del aceite en un tubo infinitamente rígido— pero se declara en 350 y 240 m/s en manguera, de modo que cortar 1 m/s de golpe levanta 11,07 bar en el tubo y sólo 3,04 o 2,09 bar en manguera; con ese mismo 22×2 en la línea de presión, 3,930 m/s producen 43,52 bar de sobrepresión sobre los 210 bar de trabajo y revientan el límite de 223 bar que Barlow admite con coeficiente 4. Y lo cuarto es que la conducción barata sale cara: en presión, tres líneas de tubo 18×2 cuestan 192,00 € de compra pero 320,59 € de energía en cinco años —512,59 € en total—, mientras que un solo 35×5 de 242,40 € gasta 72,21 € y cierra en 314,61 €; comprar por precio de etiqueta sale un 63 % más caro, o dicho al revés, el montaje bien dimensionado ahorra el 39 % del coste de vida. El censo de criterios lo remata: el arranque en frío tumba él solo 108 montajes —más de la mitad de los 192 que sobreviven—, y la compatibilidad de presión invalida 162 pero jamás en solitario: en 108 de ellos el golpe también suspende y en los 54 restantes es otro criterio el que acompaña. Toda cifra del simulador procede de un motor sellado independiente verificado con 99 388 comprobaciones, y el laboratorio construido se ha vuelto a comprobar en un navegador real con otras 459.",
  estado: "activo",
  simuladorHtml: "/labs/perdidas-carga-conducciones.html",
};

export default catalogo;
