import type { BriefingConfig } from '@/components/MissionBriefing';

const briefing: BriefingConfig = {
  codigo: 'MEC-104',
  titulo: 'Controla Cargas Negativas con Válvula de Contrabalance',
  subtitulo: 'Hidráulica y Neumática · ISO 4413 + Routh–Hurwitz: la carga que baja sola y el lazo que cabecea',
  acento: '#4FC3B0',
  duracion: 45,
  videoUrl: '',
  bienvenida: `Una carga negativa es la que tira en el mismo sentido en el que quieres moverla. El problema no es que baje: es que baja SOLA.

Lo primero que vas a medir es que esa carga ya está presurizando el circuito con la máquina parada. La pluma articulada de este banco cuelga 68,0 kN sobre 12 272 mm² de cámara resistente, y el manómetro marca 55,4 bar sin que nadie haya arrancado la bomba. Es presión INDUCIDA: la firma de la carga en el aceite. Y no tiene que ver con el tamaño de la máquina sino con la relación entre carga y área: el cabrestante, que mueve tres veces menos fuerza que la pluma, induce 138,2 bar porque su área equivalente es ocho veces menor.

De ahí sale el tarado mínimo, y ahí está la primera trampa. El criterio de sujeción pide un 30 % por encima: 1,3 · 55,4 = 72,0 bar. Los 70 del catálogo, que parecen bastar, se quedan a DOS bar. Parece una tontería hasta que recuerdas lo que hay al otro lado.

Lo segundo es el equilibrio del carrete, que cabe en una línea: p_res + R·p_mot = tarado + f_bp·p_Bp + Δp_ov. Todo el laboratorio sale de despejarla. El término que casi nadie mira es f_bp, y no es una constante: es una propiedad del DRENAJE del muelle. Vale 1 + R con drenaje interno, 1 con balanceado y 0 con el muelle ventilado al tanque. En la pluma hay 6 bar de contrapresión en el retorno: con relación 1,5:1 el muelle ve 15,0 bar, y con 10:1 ve 66,0. Seis bar que nadie mide acaban costando sesenta y seis, y ventilar el muelle los borra de un plumazo por cinco unidades de coste.

Lo tercero contradice la intuición energética. Al bajar la pluma, la bomba aporta 1,68 kW. El calor total es 5,71. Los 4,04 kW que faltan los pone la carga al caer: F·v = 68 000 N a 59,4 mm/s. Bajar una carga no cuesta energía, la REGALA, y alguien tiene que tragársela. El calor de una contrabalance no es un defecto: es su función.

Lo cuarto es lo que separa este laboratorio de un catálogo de componentes: la contrabalance es un LAZO CERRADO. Aplicando Routh–Hurwitz al polinomio del lazo linealizado, con la compresibilidad del aceite (β = 1,4 GPa) como resorte, la condición se reduce a una desigualdad que cabe en una servilleta: R·A_mot·V_res < A_res·V_mot. Ni la masa de la carga ni la ganancia del carrete aparecen en ella. En la pluma con manguera corta las raíces van de −0,48 ± 94,47i con 1,5:1 a +3,81 ± 94,84i con 10:1: la frecuencia se queda entre 15,04 y 15,09 Hz y lo que cruza es la parte real. Por eso todas las contrabalances inestables suenan igual; lo que cambia es si el cabeceo se apaga o crece.

Y como V_res lo fija el MONTAJE, el mismo hardware pasa de inestable a estable atornillándolo en otro sitio: el cabrestante a 4,5:1 tiene margen 0,61 en el bloque de mando y 1,39 abridado al actuador. No has tocado la válvula. Has quitado 3,45 m de manguera, y esa manguera era el resorte del lazo.

Lo quinto es que el tarado no sólo sujeta: cierra el asiento, y el efecto es exponencial. Una década de fuga por cada 0,2 de la relación presión inducida / tarado, corregida por la viscosidad real del aceite. La prensa trabaja a 65 °C, donde el VG 46 es 2,687 veces menos viscoso que a 40, y su útil está en contacto con la pieza: con 70 bar deriva 0,349 mm en diez minutos contra los 0,30 que admite. Es la única estación del banco que suspende la fuga ella sola.

Y lo sexto es que la misma válvula que sujeta puede reventar el cilindro. En la prensa, que baja por el fondo, la cámara resistente es la corona y φ = 1,457: tarar a 280 bar lleva la corona a 170,8 cuando el cilindro admite 160. El tarado no cuesta un euro en el orden de coste, y sin embargo es lo que rompe el componente.

El banco tiene cinco estaciones industriales y 1 125 configuraciones (5 relaciones × 5 tarados × 3 drenajes × 3 montajes × 5 estaciones). Sólo 61 cumplen los seis criterios a la vez, y en la plataforma de tijera —con personas a bordo— sobrevive exactamente UNA de 225. Motor verificado con 28 829 comprobaciones numéricas, 0 fallos, y la simulación con 157 aserciones en navegador real.`,
  conceptos: [
    { icono: '⬇️', nombre: 'La carga ya presurizó el circuito antes de arrancar', descripcion: 'p_ind = 10·F/A_res es la presión que una carga negativa pone en la cámara resistente con la máquina parada: 55,4 bar en la pluma, 48,4 en la tijera, 47,2 en el volquete, 49,9 en la prensa y 138,2 en el cabrestante. De ella cuelga el criterio de sujeción, tarado ≥ 1,3·p_ind, que da tarados mínimos de 72,0 · 62,9 · 61,4 · 64,8 y 179,7 bar. Es la razón de que la pluma no se pueda tarar a 70 aunque falten sólo dos, y de que el cabrestante —que mueve tres veces menos fuerza— necesite 179,7: lo que manda no es la carga sino la carga dividida por el área.' },
    { icono: '⚖️', nombre: 'El equilibrio del carrete y el factor de contrapresión', descripcion: 'p_res + R·p_mot = tarado + f_bp·p_Bp + Δp_ov es la ecuación entera del laboratorio, y f_bp es su término escondido: 1 + R con drenaje interno, 1 con balanceado, 0 con el muelle ventilado a tanque. En la pluma, 6 bar de contrapresión de retorno pesan 15,0 bar sobre el muelle con relación 1,5:1 y 66,0 con 10:1. Subir la relación abarata la válvula y baja el pilotaje de 33,5 a 11,6 bar, y a cambio te acopla al retorno con un factor de once y se lleva por delante la estabilidad. Los tres drenajes no son variantes de catálogo: son tres formas de decidir cuánto te importa lo que pase en el retorno.' },
    { icono: '🔥', nombre: 'Bajar una carga no cuesta energía: la regala', descripcion: 'La identidad q_b·p_mot/600 + F·v·10⁻⁶ ≡ q_res·p_res/600 se cumple en todos los puntos del banco. En el óptimo de la pluma son 1,68 kW de la bomba más 4,04 kW de la carga que cae igual a 5,71 kW que la contrabalance disipa: la mayor fuente de calor del circuito es la carga, no la bomba. Eso se paga en kWh reales con las horas de servicio de cada estación —5 142 en la pluma, 4 680 en la tijera, 2 284 en el volquete, 5 803 en la prensa y 7 342 en el cabrestante— y se comprueba contra la capacidad de disipación del depósito: la pluma evacúa 6,0 kW y su óptimo genera 5,71, pero tarada a 140 en vez de 105 generaría 6,51 y ya no cabría.' },
    { icono: '📉', nombre: 'Una contrabalance es un lazo cerrado, y el criterio es de áreas y volúmenes', descripcion: 'Routh–Hurwitz sobre el polinomio del lazo linealizado con β = 1,4 GPa se reduce a R·A_mot·V_res < A_res·V_mot, es decir ME = (A_res·V_mot)/(R·A_mot·V_res) > 1: ni la masa de la carga ni la ganancia del carrete aparecen, y el laboratorio lo demuestra moviéndolas sin que las raíces crucen. Las raíces de la pluma con manguera corta van de −0,48 ± 94,47i a +3,81 ± 94,84i según la relación, con la frecuencia clavada entre 15,04 y 15,09 Hz. Y como V_res lo fija el montaje, el cabrestante a 4,5:1 pasa de margen 0,61 en el bloque de mando a 1,39 abridado: la manguera de retorno ES el resorte del lazo, y acortarla es estabilizar.' },
  ],
  mision: [
    'LA CARGA YA ESTÁ PRESURIZANDO EL CIRCUITO · Modo Presión inducida, estación Pluma articulada. La máquina está parada y el manómetro de la cámara resistente marca 55,4 bar: son 68 000 N repartidos sobre 12 272 mm². Recorre las cinco estaciones y comprueba que la presión inducida no tiene nada que ver con el tamaño de la máquina: el cabrestante mueve 22,0 kN —tres veces menos que la pluma— e induce 138,2 bar porque su área equivalente, sacada de cilindrada, reducción y radio de tambor, es de sólo 1 592 mm².',
    'POR QUÉ 70 BAR NO BASTAN AUNQUE LO PAREZCAN · Sigue en la pluma con el tarado en 70: el piloto de sujeción está rojo porque hacen falta 1,3 · 55,4 = 72,0 y faltan dos. Sube a 105 y mira además la deriva: pasa de 0,278 mm en diez minutos a 0,013. Ahora pon la prensa de conformado con 70 bar: la sujeción PASA —hacen falta 64,8— pero se pone rojo el piloto de fuga, 0,349 mm contra 0,30 de tolerancia, porque trabaja a 65 °C con un aceite 2,687 veces menos viscoso y su útil está en contacto con la pieza. Es la única estación que suspende la fuga ella sola.',
    'LOS 4 kW QUE LA BOMBA NO PONE · Modo Descenso, pluma con su óptimo (1,5:1, 105 bar, drenaje interno). La bomba aporta 1,68 kW, el calor total es 5,71 y los 4,04 que faltan los pone la carga al caer: 68 000 N a 59,4 mm/s. Comprueba la identidad en la telemetría, que la muestra con sus tres términos, y saca la consecuencia: una contrabalance no es un componente ineficiente, es el sitio donde se quema una energía que la máquina no puede evitar recibir. En el volquete son 7,61 kW, de los cuales 5,97 los pone la caja al caer.',
    'LA CONTRABALANCE PUEDE ROMPER EL CILINDRO · Sigue en Descenso y pon la prensa, que baja por el fondo y tiene la corona como cámara resistente: φ = 1,457. Sube el tarado a 280 bar y lee la presión de la corona: 170,8 bar sobre los 160 que aguanta el cilindro, con el piloto de presión en rojo. Baja a 210 y son 136,3; con 105, 84,5. En esta estación la contrabalance no reparte presión, la MULTIPLICA, y el límite del componente deja de ser el tarado del limitador para pasar a ser el del cilindro.',
    'SEIS BAR QUE NADIE MIRA CUESTAN SESENTA Y SEIS · Modo Pilotaje, pluma, 1,5:1 y drenaje interno: la contrapresión de retorno vale 6 bar y f_bp = 2,5, así que el muelle ve 15,0. Sube a 10:1 y la presión de pilotaje baja a 11,6 bar, que es lo que buscabas… pero f_bp sube a 11 y esos mismos 6 bar ahora pesan 66,0. Cambia el drenaje a ventilado a tanque: f_bp pasa a 0, la contrapresión desaparece de la ecuación y el pilotaje cae a 5,5 bar. Cuesta cinco unidades; el balanceado cuesta tres y deja f_bp = 1.',
    'LAS RAÍCES CRUZAN SIN CAMBIAR DE TONO · Modo Estabilidad, pluma con manguera corta y 1,5:1: raíces en −2,23 y −0,48 ± 94,47i, todas a la izquierda, margen 1,63. Sube a 3:1 y aparecen dos en +0,29: margen 0,81, el lazo diverge. Fíjate en la parte imaginaria: 94,47 antes y 94,49 después, o sea 15,04 Hz en los dos casos. Comprueba después los dos lados de la desigualdad en la telemetría —R·A_mot·V_res frente a A_res·V_mot— y verifica que ni la masa de la carga ni la ganancia del carrete aparecen por ninguna parte.',
    'EL MISMO HARDWARE, OTRO SITIO · Pon el cabrestante con 4,5:1 en el bloque de mando: margen 0,61, inestable. Cambia SÓLO el montaje a brida sobre el actuador: 1,39, estable. No has tocado la válvula, ni el tarado, ni el drenaje, ni la carga: has quitado 3,45 m de manguera del lado resistente. Mira luego la tabla de relaciones críticas, que va de 2,74 en el bloque a 6,24 abridada en esta estación, y de 2,28 a 2,49 en la pluma: es el número que explica por qué la misma válvula vale en una máquina y no en la de al lado.',
    'RETO · Se sortea una estación y arrancas con los cuatro ejes mal a propósito. Elige relación de pilotaje, tarado, drenaje y montaje y pulsa Comprobar: cada eje se califica POR SEPARADO con los otros tres ya en su óptimo, así que sabrás cuál fallaste sin que te den la respuesta, y hay una pista que destapa un solo eje. Cumplir los seis criterios no basta: hay que montar el conjunto válido más barato y, a igualdad de coste, el que menos caliente. De las 1 125 configuraciones del banco sólo 61 son válidas, y si te toca la plataforma de tijera ten paciencia: de sus 225 sobrevive UNA, y no es la barata.',
  ],
  aplicaciones: [
    { area: 'Proyecto y selección de la contrabalance de un eje que baja por gravedad', ejemplo: 'Plumas, cabezales, plataformas, volquetes, contrapesos y cabrestantes: todo eje que pueda desplazarse por gravedad entra en el alcance de la ISO 4413, que exige medios que impidan su caída ante un fallo de la conducción y justificar la selección frente a las condiciones REALES de servicio. Este laboratorio pone sobre la mesa los seis criterios que hay que cumplir a la vez —sujeción, fuga, apertura, presión del componente, estabilidad y disipación— y demuestra que se pelean: subir el tarado cierra el asiento y revienta el cilindro por intensificación, subir la relación de pilotaje abarata la válvula y se lleva la estabilidad, y el drenaje barato es el que multiplica la contrapresión del retorno. De 1 125 configuraciones sólo 61 sobreviven, y en la plataforma de tijera con personas a bordo sólo una de 225.' },
    { area: 'Diagnóstico del cabeceo: la máquina que baja a saltos', ejemplo: 'Es la avería que todo el mundo achaca al aceite o al aire, y casi nunca lo es. Aquí se mide su causa real: la contrabalance forma un lazo cerrado con la compresibilidad del aceite de las dos cámaras, y la condición de estabilidad se reduce a R·A_mot·V_res < A_res·V_mot. Como no aparecen ni la masa ni la ganancia del carrete, cambiar de carga o de marca de válvula no arregla nada; lo que arregla es bajar la relación de pilotaje o acortar la manguera del lado resistente. El cabrestante del banco pasa de margen 0,61 a 1,39 pasándolo del bloque de mando a la brida del actuador, y las raíces enseñan por qué el ruido es siempre el mismo: la frecuencia se queda en 15,04–15,09 Hz y lo único que cambia de signo es el amortiguamiento.' },
    { area: 'Auditoría energética y de deriva de máquinas con carga suspendida', ejemplo: 'Dos usos en el mismo banco. En energía, toda la energía potencial de la carga se disipa en la contrabalance y se puede contar: 5 142 kWh al año en la pluma, 7 342 en el cabrestante, y de esos totales la parte que pone la bomba es minoritaria —1,68 de 5,71 kW en la pluma—, lo que es en sí mismo el argumento para plantear recuperación con acumulador. En mantenimiento, la deriva de una carga parada mide el estado del asiento: el modelo la calcula como exponencial de la relación presión inducida / tarado corregida por la viscosidad a la temperatura real, y explica por qué una prensa a 65 °C con el útil en contacto tiene una tolerancia diez veces más estrecha que una pluma, y por qué la misma válvula que allí sobra aquí suspende.' },
  ],
};

export default briefing;
